"use client";
import {FormEvent,useEffect,useState} from "react";

type Job={id:string;patient:string;clinic:string;work:number;workName?:string;workCategory?:string;teeth:string;tech:string;assistant?:string;courier?:string;feeTech?:number;feeAssistant?:number;feeCourier?:number;status:string;due:string;price:number;paid:number};
type Stock={id:number;sku:string;name:string;unit:string;qty:number;min:number;cost:number};
type Move={id:number;stock:number;type:string;qty:number;date:string;note:string};
type Cash={id:number;type:"Masuk"|"Keluar";category:string;amount:number;date:string;note:string};
type Role="Owner"|"Admin"|"Teknisi"|"Asisten Teknisi"|"Kurir";
type User={id:number;name:string;role:Role;tech?:string;active:boolean};
type ExtraBonus={id:number;tech:string;amount:number;note:string;date:string};
const workerRoles:Role[]=["Teknisi","Asisten Teknisi","Kurir"];
const handlesJob=(u:User,j:Job)=>u.role==="Teknisi"?j.tech===u.name:u.role==="Asisten Teknisi"?j.assistant===u.name:u.role==="Kurir"?j.courier===u.name:false;
const jobFee=(u:User,j:Job)=>u.role==="Teknisi"?(j.feeTech||0):u.role==="Asisten Teknisi"?(j.feeAssistant||0):u.role==="Kurir"?(j.feeCourier||0):0;
const nextId=(items:{id:number}[])=>items.reduce((max,item)=>Math.max(max,item.id),0)+1;
const jobs0:Job[]=[];
const stock0:Stock[]=[];
const cash0:Cash[]=[];
const users0:User[]=[{id:1,name:"Rizky Prasetyo",role:"Owner",active:true}];
const menus=["Dashboard","Pekerjaan","Stok Bahan","Barang Masuk/Keluar","Keuangan","Fee Tim","Akun & Akses","Laporan"],icons=["⌂","◈","▣","⇅","◒","★","♙","▤"],rp=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
function useStored<T>(key:string,start:T){const[v,setV]=useState(start),[ready,setReady]=useState(false);useEffect(()=>{const id=window.setTimeout(()=>{const x=localStorage.getItem(key);if(x)setV(JSON.parse(x));setReady(true)},0);return()=>window.clearTimeout(id)},[key]);useEffect(()=>{if(ready)localStorage.setItem(key,JSON.stringify(v))},[key,ready,v]);return[v,setV]as const}

export default function Home(){
 const[active,setActive]=useState("Dashboard"),[search,setSearch]=useState(""),[modal,setModal]=useState(""),[userId,setUserId]=useState(1),[selectedJob,setSelectedJob]=useState<Job|null>(null);
 const[jobs,setJobs]=useStored("dl-v5-jobs",jobs0),[stocks,setStocks]=useStored("dl-v5-stock",stock0),[moves,setMoves]=useStored<Move[]>("dl-v5-moves",[]),[cash,setCash]=useStored("dl-v5-cash",cash0),[users,setUsers]=useStored("dl-v5-users",users0),[extras,setExtras]=useStored<ExtraBonus[]>("dl-v5-extra-bonus",[]);
 const me=users.find(u=>u.id===userId)||users[0],manage=me.role==="Owner"||me.role==="Admin",visibleMenus=manage?menus:["Dashboard","Pekerjaan","Fee Tim"],income=cash.filter(x=>x.type==="Masuk").reduce((s,x)=>s+x.amount,0),expense=cash.filter(x=>x.type==="Keluar").reduce((s,x)=>s+x.amount,0),done=jobs.filter(j=>j.status==="Selesai"),autoBonus=done.reduce((s,j)=>s+(j.feeTech||0)+(j.feeAssistant||0)+(j.feeCourier||0),0),bonus=autoBonus+extras.reduce((s,x)=>s+x.amount,0),low=stocks.filter(x=>x.qty<=x.min);
 const assigned=(j:Job)=>manage||(me.role==="Teknisi"&&j.tech===me.name)||(me.role==="Asisten Teknisi"&&j.assistant===me.name)||(me.role==="Kurir"&&j.courier===me.name);
 const list=jobs.filter(j=>assigned(j)&&`${j.id} ${j.patient} ${j.clinic} ${j.workName||""}`.toLowerCase().includes(search.toLowerCase()));
 const submitJob=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setJobs([{id:`DL-${new Date().toISOString().slice(2,10).replaceAll("-","")}-${String(jobs.length+1).padStart(3,"0")}`,patient:String(f.get("patient")),clinic:String(f.get("clinic")),work:0,workName:String(f.get("workName")),workCategory:String(f.get("workCategory")),teeth:String(f.get("teeth")),tech:String(f.get("tech")),assistant:String(f.get("assistant")),courier:String(f.get("courier")),feeTech:Number(f.get("feeTech"))||0,feeAssistant:Number(f.get("feeAssistant"))||0,feeCourier:Number(f.get("feeCourier"))||0,status:"Model",due:String(f.get("due")),price:Number(f.get("price"))||0,paid:0},...jobs]);setModal("");setActive("Pekerjaan")};
 const advanceJob=(j:Job)=>{const stages=["Model","Produksi","Finishing","QC","Selesai"],next=stages[Math.min(stages.indexOf(j.status)+1,stages.length-1)];if(j.status==="Selesai")return;if(next==="Selesai"){setSelectedJob(j);setModal("complete");return}if(confirm(`Lanjutkan ${j.id} dari ${j.status} ke ${next}?`))setJobs(jobs.map(x=>x.id===j.id?{...x,status:next}:x))};
 const editJobFees=(j:Job)=>{const feeTech=prompt(`Fee Teknisi ${j.tech}`,String(j.feeTech||0));if(feeTech===null)return;const feeAssistant=prompt(`Fee Asisten ${j.assistant||"(tidak ada)"}`,String(j.feeAssistant||0));if(feeAssistant===null)return;const feeCourier=prompt(`Fee Kurir ${j.courier||"(tidak ada)"}`,String(j.feeCourier||0));if(feeCourier===null)return;setJobs(jobs.map(x=>x.id===j.id?{...x,feeTech:Number(feeTech)||0,feeAssistant:Number(feeAssistant)||0,feeCourier:Number(feeCourier)||0}:x))};
 const submitMove=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),id=Number(f.get("stock")),type=String(f.get("type")),q=Number(f.get("qty"));setStocks(stocks.map(x=>x.id===id?{...x,qty:type==="Masuk"?x.qty+q:type==="Keluar"?Math.max(0,x.qty-q):q}:x));setMoves([{id:nextId(moves),stock:id,type,qty:q,date:String(f.get("date")),note:String(f.get("note"))},...moves]);setModal("")};
 const submitCash=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setCash([{id:nextId(cash),type:String(f.get("type"))as Cash["type"],category:String(f.get("category")),amount:Number(f.get("amount")),date:String(f.get("date")),note:String(f.get("note"))},...cash]);setModal("")};
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">DL</span><div><b>DentaLab Pro</b><small>Laboratory ERP</small></div></div><nav>{visibleMenus.map(m=>{const i=menus.indexOf(m);return <button key={m} className={active===m?"active":""} onClick={()=>setActive(m)}><span className="nav-icon">{icons[i]}</span>{m}{m==="Stok Bahan"&&low.length>0&&<em>{low.length}</em>}</button>})}</nav><div className="side-card"><span>●</span><div><b>Akses {me.role} aktif</b><small>{manage?"Kontrol penuh operasional":"Ruang kerja pekerja"}</small></div></div><button className="profile"><span>{me.name.slice(0,2).toUpperCase()}</span><div><b>{me.name}</b><small>{me.role}</small></div></button></aside><section className="workspace"><header className="topbar"><label className="search">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari order, pasien, atau klinik..."/></label><label className="account-switch"><small>MASUK SEBAGAI</small><select value={userId} onChange={e=>{setUserId(Number(e.target.value));setActive("Dashboard")}}>{users.filter(u=>u.active).map(u=><option value={u.id} key={u.id}>{u.name} · {u.role}</option>)}</select></label>{manage&&users.some(u=>u.role==="Teknisi"&&u.active)&&<button className="primary" onClick={()=>setModal("job")}>＋ Pekerjaan Baru</button>}</header><div className="content"><div className="heading"><div><p className="eyebrow">{me.role.toUpperCase()} WORKSPACE · 16 JULI 2026</p><h1>{active}</h1><p>{manage?"Kelola pekerjaan, tim, fee, keuangan, dan bahan dalam satu alur.":`Selamat datang ${me.name}. Perbarui progres pekerjaan Anda hari ini.`}</p></div><span className="system-live">● {me.role} terverifikasi</span></div>
 {active==="Dashboard"&&<><section className="dashboard-hero"><div><span>OPERASIONAL LAB TERPADU</span><h2>Selamat datang, {me.name}</h2><p>{manage?"Bangun alur kerja lab Anda dari awal dengan data yang bersih dan terstruktur.":"Fokus pada pekerjaan hari ini dan catat setiap progres dengan cepat."}</p></div><div className="hero-score"><strong>{jobs.filter(j=>j.status!=="Selesai").length}</strong><span>Pekerjaan aktif</span></div></section>{manage&&jobs.length===0&&<SetupGuide users={users} stocks={stocks} go={setActive} openJob={()=>setModal("job")}/>}<Metrics jobs={jobs} low={low.length} income={income} expense={expense} bonus={bonus}/><div className="main-grid"><section className="panel jobs-panel"><Head title="Pekerjaan berjalan" sub="Prioritas berdasarkan tenggat"/><JobTable jobs={list.slice(0,6)}/></section><aside className="right-stack"><section className="panel"><Head title="Stok kritis" sub="Perlu segera ditindaklanjuti"/>{low.length===0?<div className="mini-empty">Belum ada stok kritis</div>:low.map(x=><div className="stock-row" key={x.id}><span className="stock-icon red">▣</span><div><b>{x.name}</b><small>Minimum {x.min} {x.unit}</small></div><strong>{x.qty} {x.unit}</strong></div>)}</section><section className="panel cash-mini"><Head title="Keuangan bulan ini" sub="Ringkasan kas berjalan"/><p><span>Pendapatan</span><b>{rp(income)}</b></p><p><span>Pengeluaran</span><b>{rp(expense)}</b></p><p><span>Fee tim</span><b>{rp(bonus)}</b></p><p className="profit"><span>Laba operasional</span><b>{rp(income-expense-bonus)}</b></p></section></aside></div></>}
 {active==="Pekerjaan"&&<><section className="workflow-strip strong-flow"><div className="stage-model"><span>1</span><b>MODEL</b></div><i>→</i><div className="stage-production"><span>2</span><b>PRODUKSI</b></div><i>→</i><div className="stage-finishing"><span>3</span><b>FINISHING</b></div><i>→</i><div className="stage-qc"><span>4</span><b>QUALITY CONTROL</b></div><i>→</i><div className="finish"><span>✓</span><b>SELESAI & FEE</b></div></section><section className="panel page"><Toolbar title={`${list.length} pekerjaan`} sub={manage?"Kelola jenis pekerjaan, tim, fee, progres, dan pembayaran":"Daftar pekerjaan yang ditugaskan kepada Anda"} button={manage&&users.some(u=>u.role==="Teknisi")?"＋ Pekerjaan Baru":undefined} click={()=>setModal("job")}/><JobTable jobs={list} hideMoney={!manage} action={j=><div className="row-actions">{j.status!=="Selesai"&&<button className="progress-btn" onClick={()=>advanceJob(j)}>Lanjutkan →</button>}{j.status==="Selesai"&&<span className="completed-mark">✓ Terkonfirmasi</span>}{manage&&<><button onClick={()=>editJobFees(j)}>Fee</button><button onClick={()=>{const n=prompt("Harga pekerjaan",String(j.price));if(n)setJobs(jobs.map(x=>x.id===j.id?{...x,price:Number(n)}:x))}}>Harga</button><button onClick={()=>{const n=prompt("Jumlah pembayaran",String(j.price-j.paid));if(n){setJobs(jobs.map(x=>x.id===j.id?{...x,paid:Math.min(x.price,x.paid+Number(n))}:x));setCash([{id:nextId(cash),type:"Masuk",category:"Pembayaran pekerjaan",amount:Number(n),date:"2026-07-16",note:j.id},...cash])}}}>Bayar</button><button className="danger" onClick={()=>confirm(`Hapus ${j.id}?`)&&setJobs(jobs.filter(x=>x.id!==j.id))}>Hapus</button></>}</div>}/></section></>}
 {active==="Stok Bahan"&&<><div className="toolbar"><div><b>Persediaan bahan habis pakai</b><span>Nilai stok {rp(stocks.reduce((s,x)=>s+x.qty*x.cost,0))}</span></div><div className="toolbar-actions"><button className="secondary" onClick={()=>setModal("stocknew")}>＋ Tambah Bahan</button>{stocks.length>0&&<button className="primary" onClick={()=>setModal("move")}>Mutasi / Opname</button>}</div></div>{stocks.length===0?<Empty title="Belum ada bahan" text="Tambahkan bahan habis pakai pertama untuk memulai persediaan."/>:<div className="stock-grid">{stocks.map(s=><article className={`material ${s.qty<=s.min?"critical":""}`} key={s.id}><div><small>{s.sku}</small><em>{s.qty<=s.min?"KRITIS":"AMAN"}</em></div><h3>{s.name}</h3><strong>{s.qty} <small>{s.unit}</small></strong><p>Minimum {s.min} · {rp(s.cost)}/{s.unit}</p><button onClick={()=>{const n=prompt("Jumlah stok fisik",String(s.qty));if(n!==null)setStocks(stocks.map(x=>x.id===s.id?{...x,qty:Number(n)}:x))}}>Koreksi stok opname</button></article>)}</div>}</>}
 {active==="Barang Masuk/Keluar"&&<section className="panel page"><Toolbar title="Kartu stok" sub="Barang masuk, pemakaian, dan koreksi opname" button="＋ Catat Pergerakan" click={()=>setModal("move")}/><SimpleTable heads={["TANGGAL","BAHAN","JENIS","JUMLAH","KETERANGAN"]} rows={moves.map(m=>[m.date,stocks.find(s=>s.id===m.stock)?.name||"-",m.type,String(m.qty),m.note])}/></section>}
 {active==="Keuangan"&&<><Metrics jobs={jobs} low={low.length} income={income} expense={expense} bonus={bonus} finance/><section className="panel page"><Toolbar title="Buku kas laboratorium" sub="Pemasukan dan pengeluaran tercatat" button="＋ Transaksi" click={()=>setModal("cash")}/><table><thead><tr><th>TANGGAL</th><th>TIPE</th><th>KATEGORI</th><th>KETERANGAN</th><th>NOMINAL</th><th>AKSI</th></tr></thead><tbody>{cash.map(c=><tr key={c.id}><td>{c.date}</td><td>{c.type}</td><td>{c.category}</td><td>{c.note}</td><td><b>{rp(c.amount)}</b></td><td><button className="text-danger" onClick={()=>confirm("Hapus transaksi ini?")&&setCash(cash.filter(x=>x.id!==c.id))}>Hapus</button></td></tr>)}</tbody></table></section></>}
 {active==="Fee Tim"&&<><div className="toolbar"><div><b>Fee tim · Juli 2026</b><span>Fee Teknisi, Asisten Teknisi, dan Kurir tercatat otomatis saat pekerjaan selesai</span></div>{manage&&users.some(u=>workerRoles.includes(u.role)&&u.active)&&<button className="primary" onClick={()=>setModal("bonus")}>＋ Fee Tambahan</button>}</div>{users.some(u=>workerRoles.includes(u.role))?<div className="bonus-grid">{users.filter(u=>workerRoles.includes(u.role)&&(manage||u.id===me.id)).map(u=>{const completed=done.filter(j=>handlesJob(u,j)),automatic=completed.reduce((s,j)=>s+jobFee(u,j),0),extra=extras.filter(x=>x.tech===u.name).reduce((s,x)=>s+x.amount,0);return <article className="panel tech bonus-detail" key={u.id}><span>{u.name.slice(0,2).toUpperCase()}</span><div><small>{u.role.toUpperCase()}</small><h3>{u.name}</h3><p>{completed.length} pekerjaan selesai · Fee otomatis {rp(automatic)}</p><p>Tambahan owner/admin · {rp(extra)}</p></div><strong>{rp(automatic+extra)}</strong></article>})}</div>:<Empty title="Belum ada anggota produksi" text="Buat akun Teknisi, Asisten Teknisi, atau Kurir melalui menu Akun & Akses."/>}{manage&&extras.length>0&&<section className="panel extra-list"><Head title="Riwayat fee tambahan" sub="Penyesuaian fee oleh Owner atau Admin"/>{extras.map(x=><p key={x.id}><span><b>{x.tech}</b><small>{x.date} · {x.note}</small></span><strong>{rp(x.amount)}</strong><button onClick={()=>setExtras(extras.filter(e=>e.id!==x.id))}>Hapus</button></p>)}</section>}</>}
 {active==="Akun & Akses"&&manage&&<section className="panel page"><Toolbar title="Akun pengguna" sub="Buat akun Admin, Teknisi, Asisten Teknisi, dan Kurir" button="＋ Tambah Akun" click={()=>setModal("user")}/><table><thead><tr><th>NAMA</th><th>PERAN</th><th>AKSES</th><th>STATUS</th><th>AKSI</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.name}</b></td><td><span className={`role role-${u.role.toLowerCase().replaceAll(" ","-")}`}>{u.role}</span></td><td>{workerRoles.includes(u.role)?"Pekerjaan & fee sendiri":"Seluruh modul operasional"}</td><td>{u.active?"Aktif":"Nonaktif"}</td><td>{u.role!=="Owner"&&<div className="row-actions"><button onClick={()=>setUsers(users.map(x=>x.id===u.id?{...x,active:!x.active}:x))}>{u.active?"Nonaktifkan":"Aktifkan"}</button><button className="danger" onClick={()=>confirm(`Hapus akun ${u.name}?`)&&setUsers(users.filter(x=>x.id!==u.id))}>Hapus</button></div>}</td></tr>)}</tbody></table></section>}
 {active==="Laporan"&&<><section className="report"><div><p className="eyebrow">LAPORAN MANAJEMEN · JULI 2026</p><h2>Kinerja Laboratorium</h2><p>Ringkasan operasional siap cetak.</p></div><button onClick={()=>window.print()}>Cetak / Simpan PDF</button></section><div className="report-grid"><Report title="Operasional" data={[["Total order",jobs.length],["Order selesai",done.length],["Nilai pekerjaan",rp(jobs.reduce((s,j)=>s+j.price,0))],["Piutang",rp(jobs.reduce((s,j)=>s+j.price-j.paid,0))]]}/><Report title="Keuangan" data={[["Pendapatan",rp(income)],["Pengeluaran",rp(expense)],["Fee tim",rp(bonus)],["Laba",rp(income-expense-bonus)]]}/><Report title="Persediaan" data={[["Jenis bahan",stocks.length],["Stok kritis",low.length],["Nilai stok",rp(stocks.reduce((s,x)=>s+x.qty*x.cost,0))],["Status opname","Aktif"]]}/></div></>}
 </div></section>{modal&&<div className="modal-backdrop" onMouseDown={()=>{setModal("");setSelectedJob(null)}}><section className="modal job-modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal("")}>×</button>{modal==="job"&&<JobForm users={users} submit={submitJob}/>} {modal==="complete"&&selectedJob&&<CompleteForm job={selectedJob} confirm={()=>{setJobs(jobs.map(x=>x.id===selectedJob.id?{...x,status:"Selesai"}:x));setSelectedJob(null);setModal("")}}/>} {modal==="move"&&<MoveForm stocks={stocks} submit={submitMove}/>} {modal==="stocknew"&&<StockNewForm submit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setStocks([...stocks,{id:nextId(stocks),sku:String(f.get("sku")),name:String(f.get("name")),unit:String(f.get("unit")),qty:Number(f.get("qty")),min:Number(f.get("min")),cost:Number(f.get("cost"))}]);setModal("")}}/>} {modal==="cash"&&<CashForm submit={submitCash}/>} {modal==="bonus"&&<BonusForm users={users} submit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setExtras([{id:nextId(extras),tech:String(f.get("tech")),amount:Number(f.get("amount")),note:String(f.get("note")),date:"2026-07-16"},...extras]);setModal("")}}/>} {modal==="user"&&<UserForm submit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),name=String(f.get("name")),role=String(f.get("role"))as Role;setUsers([...users,{id:nextId(users),name,role,active:true}]);setModal("")}}/>}</section></div>}</main>}

function Head({title,sub}:{title:string;sub:string}){return <div className="panel-head"><div><h2>{title}</h2><p>{sub}</p></div></div>};
function Toolbar({title,sub,button,click}:{title:string;sub:string;button?:string;click?:()=>void}){return <div className="toolbar"><div><b>{title}</b><span>{sub}</span></div>{button&&<button className="primary" onClick={click}>{button}</button>}</div>}
function Metrics({jobs,low,income,expense,bonus,finance}:{jobs:Job[];low:number;income:number;expense:number;bonus:number;finance?:boolean}){const data=finance?[["↓",rp(income),"Total pemasukan"],["↑",rp(expense),"Total pengeluaran"],["=",rp(income-expense-bonus),"Laba setelah fee tim"]]:[["◈",jobs.filter(j=>j.status!=="Selesai").length,"Pekerjaan aktif"],["✓",jobs.filter(j=>j.status==="Selesai").length,"Selesai bulan ini"],["▣",low,"Stok kritis"],["Rp",rp(income-expense-bonus),"Laba operasional"]];return <div className={`metrics ${finance?"three":""}`}>{data.map((x,i)=><article key={String(x[2])}><span className={["mint","blue","orange","violet"][i]}>{x[0]}</span><strong>{x[1]}</strong><p>{x[2]}</p><small>Data bulan Juli 2026</small></article>)}</div>}
function JobTable({jobs,action,hideMoney}:{jobs:Job[];action?:(j:Job)=>React.ReactNode;hideMoney?:boolean}){return <div className="table-wrap"><table><thead><tr><th>ORDER & PASIEN</th><th>JENIS PEKERJAAN</th><th>TIM PRODUKSI & FEE</th><th>TENGGAT</th><th>PROGRES</th>{!hideMoney&&<th>TAGIHAN</th>}{action&&<th>AKSI</th>}</tr></thead><tbody>{jobs.map(j=><tr key={j.id}><td><b>{j.id}</b><span>{j.patient} · {j.clinic}</span></td><td><b>{j.workName||"Belum diisi"}</b><span>{j.workCategory||"Umum"} · Gigi {j.teeth||"-"}</span></td><td><div className="team-stack"><span><b>T</b>{j.tech} · {rp(j.feeTech||0)}</span>{j.assistant&&<span><b>A</b>{j.assistant} · {rp(j.feeAssistant||0)}</span>}{j.courier&&<span><b>K</b>{j.courier} · {rp(j.feeCourier||0)}</span>}</div></td><td><b>{j.due}</b></td><td><span className={`status s-${j.status.toLowerCase()}`}>{j.status}</span></td>{!hideMoney&&<td><b>{rp(j.price-j.paid)}</b><span>{j.paid===j.price?"Lunas":"Belum lunas"} · Fee tim {rp((j.feeTech||0)+(j.feeAssistant||0)+(j.feeCourier||0))}</span></td>}{action&&<td>{action(j)}</td>}</tr>)}</tbody></table>{jobs.length===0&&<Empty title="Belum ada pekerjaan" text="Buat akun Teknisi lalu catat pekerjaan pertama langsung dari halaman ini."/>}</div>}
function Empty({title,text}:{title:string;text:string}){return <div className="empty-state"><span>◇</span><b>{title}</b><p>{text}</p></div>}
function SetupGuide({users,stocks,go,openJob}:{users:User[];stocks:Stock[];go:(x:string)=>void;openJob:()=>void}){const hasTech=users.some(u=>u.role==="Teknisi"&&u.active),steps=[{done:users.some(u=>workerRoles.includes(u.role)),n:"01",title:"Buat akun tim",text:"Teknisi, Asisten, dan Kurir",run:()=>go("Akun & Akses")},{done:false,n:"02",title:"Catat pekerjaan",text:"Isi jenis, harga, tim, dan fee",run:hasTech?openJob:()=>go("Akun & Akses")},{done:stocks.length>0,n:"03",title:"Masukkan bahan",text:"Catat stok dan batas minimum",run:()=>go("Stok Bahan")}];return <section className="setup-guide"><div className="setup-head"><div><span>PERSIAPAN AWAL</span><h3>Siapkan sistem dalam 3 langkah</h3></div><strong>{steps.filter(s=>s.done).length}/3 selesai</strong></div><div className="setup-steps">{steps.map(s=><button key={s.n} className={s.done?"done":""} onClick={s.run}><i>{s.done?"✓":s.n}</i><span><b>{s.title}</b><small>{s.text}</small></span><em>→</em></button>)}</div></section>}
function SimpleTable({heads,rows}:{heads:string[];rows:string[][]}){return <table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table>}
function Report({title,data}:{title:string;data:(string|number)[][]}){return <article className="panel report-card"><h3>{title}</h3>{data.map((x,i)=><p key={i}><span>{x[0]}</span><b>{x[1]}</b></p>)}</article>}
const F=({label,children}:{label:string;children:React.ReactNode})=><label>{label}{children}</label>;
function JobForm({users,submit}:{users:User[];submit:(e:FormEvent<HTMLFormElement>)=>void}){return <><p className="eyebrow">ORDER BARU · DATA, TIM & FEE</p><h2>Catat pekerjaan masuk</h2><div className="form-flow"><b>Model</b><i>→</i><span>Produksi</span><i>→</i><span>Finishing</span><i>→</i><span>QC</span><i>→</i><span>Selesai & fee</span></div><form onSubmit={submit}><div className="form-section"><h3>Informasi pekerjaan</h3><div className="form-grid"><F label="Nama pasien"><input name="patient" required/></F><F label="Klinik / dokter"><input name="clinic" required/></F><F label="Jenis pekerjaan"><input name="workName" required placeholder="Contoh: Valplast, Crown Zirconia"/></F><F label="Kategori"><select name="workCategory"><option>Gigi Palsu Lepasan</option><option>Crown & Bridge</option><option>Implan</option><option>Orthodonti</option><option>Repair</option><option>Lainnya</option></select></F><F label="Nomor gigi / rahang"><input name="teeth" placeholder="Contoh: 11-13 / RA"/></F><F label="Target selesai"><input type="date" name="due" required/></F></div></div><div className="form-section fee-section"><h3>Tim produksi & fee per pekerjaan</h3><div className="form-grid"><F label="Teknisi"><select name="tech" required>{users.filter(u=>u.role==="Teknisi"&&u.active).map(u=><option key={u.id}>{u.name}</option>)}</select></F><F label="Fee Teknisi"><input type="number" min="0" name="feeTech" required placeholder="Rp"/></F><F label="Asisten Teknisi (opsional)"><select name="assistant"><option value="">Tanpa asisten</option>{users.filter(u=>u.role==="Asisten Teknisi"&&u.active).map(u=><option key={u.id}>{u.name}</option>)}</select></F><F label="Fee Asisten Teknisi"><input type="number" min="0" name="feeAssistant" placeholder="Rp"/></F><F label="Kurir (opsional)"><select name="courier"><option value="">Tanpa kurir</option>{users.filter(u=>u.role==="Kurir"&&u.active).map(u=><option key={u.id}>{u.name}</option>)}</select></F><F label="Fee Kurir"><input type="number" min="0" name="feeCourier" placeholder="Rp"/></F></div></div><div className="form-section price-section"><F label="Harga pekerjaan ke pelanggan"><input type="number" min="0" name="price" required placeholder="Rp"/></F></div><button className="primary save">Simpan & mulai dari tahap Model</button></form></>}
function CompleteForm({job,confirm}:{job:Job;confirm:()=>void}){const total=(job.feeTech||0)+(job.feeAssistant||0)+(job.feeCourier||0);return <div className="complete-modal"><span className="complete-icon">✓</span><p className="eyebrow">KONFIRMASI AKHIR</p><h2>Selesaikan pekerjaan?</h2><p>Pastikan <b>{job.workName}</b> untuk order <b>{job.id}</b> telah melewati Quality Control dan siap diserahkan.</p><div className="complete-summary fee-confirm"><span><small>Teknisi · {job.tech}</small><b>{rp(job.feeTech||0)}</b></span><span><small>Asisten · {job.assistant||"Tidak ada"}</small><b>{rp(job.feeAssistant||0)}</b></span><span><small>Kurir · {job.courier||"Tidak ada"}</small><b>{rp(job.feeCourier||0)}</b></span><span className="fee-total"><small>Total fee tim</small><b>{rp(total)}</b></span></div><div className="confirm-note">Setelah dikonfirmasi, status menjadi <b>Selesai</b> dan seluruh fee tim otomatis masuk ke laporan bulan berjalan.</div><button className="primary save" onClick={confirm}>✓ Konfirmasi selesai & catat fee tim</button></div>}
function MoveForm({stocks,submit}:{stocks:Stock[];submit:(e:FormEvent<HTMLFormElement>)=>void}){return <><p className="eyebrow">PERSEDIAAN</p><h2>Mutasi & stok opname</h2><form onSubmit={submit}><div className="form-grid"><F label="Bahan"><select name="stock">{stocks.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></F><F label="Jenis"><select name="type"><option>Masuk</option><option>Keluar</option><option>Stok Opname</option></select></F><F label="Jumlah"><input type="number" step=".01" name="qty" required/></F><F label="Tanggal"><input type="date" name="date" defaultValue="2026-07-15"/></F><F label="Keterangan"><input name="note"/></F></div><button className="primary save">Simpan pergerakan</button></form></>}
function CashForm({submit}:{submit:(e:FormEvent<HTMLFormElement>)=>void}){return <><p className="eyebrow">BUKU KAS</p><h2>Transaksi baru</h2><form onSubmit={submit}><div className="form-grid"><F label="Jenis"><select name="type"><option>Masuk</option><option>Keluar</option></select></F><F label="Kategori"><input name="category" required/></F><F label="Nominal"><input type="number" name="amount" required/></F><F label="Tanggal"><input type="date" name="date" defaultValue="2026-07-15"/></F><F label="Keterangan"><input name="note"/></F></div><button className="primary save">Simpan transaksi</button></form></>}
function BonusForm({users,submit}:{users:User[];submit:(e:FormEvent<HTMLFormElement>)=>void}){return <><p className="eyebrow">FEE TAMBAHAN</p><h2>Tambahan untuk anggota tim</h2><form onSubmit={submit}><div className="form-grid"><F label="Pekerja"><select name="tech">{users.filter(u=>workerRoles.includes(u.role)&&u.active).map(u=><option value={u.name} key={u.id}>{u.name} · {u.role}</option>)}</select></F><F label="Nominal tambahan"><input type="number" min="0" name="amount" required/></F><F label="Keterangan"><input name="note" placeholder="Contoh: lembur order urgent" required/></F></div><button className="primary save">Tambahkan fee</button></form></>}
function StockNewForm({submit}:{submit:(e:FormEvent<HTMLFormElement>)=>void}){return <><p className="eyebrow">MASTER BAHAN</p><h2>Tambah bahan habis pakai</h2><form onSubmit={submit}><div className="form-grid"><F label="Kode / SKU"><input name="sku" required/></F><F label="Nama bahan"><input name="name" required/></F><F label="Satuan"><input name="unit" required placeholder="pcs, box, gram, disc"/></F><F label="Stok awal"><input type="number" step=".01" name="qty" required/></F><F label="Batas minimum"><input type="number" step=".01" name="min" required/></F><F label="Harga per satuan"><input type="number" name="cost" required/></F></div><button className="primary save">Simpan bahan</button></form></>}
function UserForm({submit}:{submit:(e:FormEvent<HTMLFormElement>)=>void}){return <><p className="eyebrow">AKUN PENGGUNA</p><h2>Tambah anggota tim</h2><form onSubmit={submit}><div className="form-grid"><F label="Nama lengkap"><input name="name" required/></F><F label="Jenis pekerjaan / peran"><select name="role"><option>Teknisi</option><option>Asisten Teknisi</option><option>Kurir</option><option>Admin</option></select></F></div><div className="access-note"><b>Aturan akses</b><p>Owner dan Admin mengelola seluruh operasional. Teknisi, Asisten Teknisi, dan Kurir hanya melihat pekerjaan serta fee miliknya sendiri.</p></div><button className="primary save">Buat akun</button></form></>}
