"use client";

import Image from "next/image";
import { FormEvent, ReactNode, useEffect, useState } from "react";

type PaymentStatus = "Pending" | "DP" | "Lunas";
type Role = "Owner" | "Admin" | "Teknisi" | "Asisten Teknisi" | "Kurir";
type User = { id: number; name: string; username: string; role: Role; active: boolean };
type Job = { id: string; patient: string; clinic: string; partnerId?: number; workName: string; workCategory: string; teeth: string; tech: string; assistant?: string; courier?: string; feeTech: number; feeAssistant: number; feeCourier: number; status: string; due: string; price: number; paid: number; paymentStatus: PaymentStatus };
type Stock = { id: number; sku: string; name: string; unit: string; qty: number; min: number; cost: number };
type Move = { id: number; stock: number; type: "Masuk" | "Keluar" | "Stok Opname"; qty: number; previousQty?: number; date: string; note: string };
type Cash = { id: number; type: "Masuk" | "Keluar"; category: string; amount: number; date: string; note: string };
type Extra = { id: number; tech: string; amount: number; note: string; date: string };
type Partner = { id: number; doctor: string; clinic: string; phone: string; email: string; rewardPoints: number; lastReward: string; promo: string; promoAt: string; active: boolean };
type Brand = { name: string; subtitle: string; logo: string };
type State = { jobs: Job[]; stocks: Stock[]; moves: Move[]; cash: Cash[]; extras: Extra[]; partners: Partner[]; brand: Brand };
type Bootstrap = { initialized: boolean; user: User | null; users: User[]; state: State | null };

const initial: State = { jobs: [], stocks: [], moves: [], cash: [], extras: [], partners: [], brand: { name: "DentaLab Pro", subtitle: "Laboratory ERP", logo: "" } };
const roles: Role[] = ["Teknisi", "Asisten Teknisi", "Kurir"];
const menus = ["Dashboard", "Pekerjaan", "Dokter & Klinik", "Stok Bahan", "Barang Masuk/Keluar", "Keuangan", "Fee Tim", "Akun & Akses", "Pengaturan Lab", "Laporan"];
const icons = ["⌂", "◈", "♡", "▣", "⇅", "◒", "★", "♙", "⚙", "▤"];
const rp = (n: number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(n || 0);
const id = <T extends { id: number }>(items: T[]) => items.reduce((m, x) => Math.max(m, x.id), 0) + 1;
const today = () => new Date().toISOString().slice(0, 10);
const fileData = (file: File) => new Promise<string>((resolve, reject) => { const r = new FileReader(); r.onload = () => resolve(String(r.result)); r.onerror = reject; r.readAsDataURL(file); });

async function request(body?: Record<string, unknown>) {
  const response = await fetch("/api/dentalab", { method: body ? "POST" : "GET", headers: body ? { "Content-Type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined, credentials: "same-origin", cache: "no-store" });
  const result = await response.json();
  if (!response.ok) throw new Error(result.error || "Server tidak dapat memproses permintaan.");
  return result;
}

export default function DentalabClient() {
  const [ready, setReady] = useState(false);
  const [initialized, setInitialized] = useState(false);
  const [me, setMe] = useState<User | null>(null);
  const [users, setUsers] = useState<User[]>([]);
  const [data, setData] = useState<State>(initial);
  const [active, setActive] = useState("Dashboard");
  const [search, setSearch] = useState("");
  const [modal, setModal] = useState("");
  const [error, setError] = useState("");
  const [selectedJob, setSelectedJob] = useState<Job | null>(null);
  const [selectedStock, setSelectedStock] = useState<Stock | null>(null);
  const [selectedPartner, setSelectedPartner] = useState<Partner | null>(null);

  const apply = (payload: Bootstrap) => {
    setInitialized(payload.initialized);
    setMe(payload.user);
    setUsers(payload.users || []);
    if (payload.state) setData({ ...initial, ...payload.state });
    setReady(true);
  };

  useEffect(() => { request().then(apply).catch((e) => { setError(e.message); setReady(true); }); }, []);

  const save = <K extends keyof State>(key: K, value: State[K]) => {
    setData((current) => ({ ...current, [key]: value }));
    request({ action: "saveState", key, value }).catch((e) => { alert(e.message); request().then(apply); });
  };

  const auth = async (event: FormEvent<HTMLFormElement>, action: "setup" | "login") => {
    event.preventDefault(); setError("");
    const form = new FormData(event.currentTarget);
    try { apply(await request({ action, labName: form.get("labName"), name: form.get("name"), username: form.get("username"), password: form.get("password") })); }
    catch (e) { setError((e as Error).message); }
  };

  const logout = async () => { await request({ action: "logout" }); setMe(null); setUsers([]); setActive("Dashboard"); };
  if (!ready) return <AuthLoading brand={data.brand} />;
  if (!initialized) return <OwnerSetup brand={data.brand} error={error} submit={(e) => auth(e, "setup")} />;
  if (!me) return <Login brand={data.brand} error={error} submit={(e) => auth(e, "login")} />;

  const owner = me.role === "Owner";
  const manager = owner || me.role === "Admin";
  const visibleMenus = owner ? menus : manager ? menus.filter((x) => x !== "Keuangan" && x !== "Laporan") : ["Dashboard", "Pekerjaan", "Fee Tim"];
  const { jobs, stocks, moves, cash, extras, partners, brand } = data;
  const done = jobs.filter((j) => j.status === "Selesai");
  const low = stocks.filter((s) => s.qty <= s.min);
  const income = cash.filter((c) => c.type === "Masuk").reduce((s, c) => s + c.amount, 0);
  const expense = cash.filter((c) => c.type === "Keluar").reduce((s, c) => s + c.amount, 0);
  const feeTotal = done.reduce((s, j) => s + j.feeTech + j.feeAssistant + j.feeCourier, 0) + extras.reduce((s, x) => s + x.amount, 0);
  const assigned = (job: Job) => manager || (me.role === "Teknisi" ? job.tech === me.name : me.role === "Asisten Teknisi" ? job.assistant === me.name : job.courier === me.name);
  const list = jobs.filter((j) => assigned(j) && `${j.id} ${j.patient} ${j.clinic} ${j.workName}`.toLowerCase().includes(search.toLowerCase()));
  const workers = users.filter((u) => roles.includes(u.role) && u.active);

  const close = () => { setModal(""); setSelectedJob(null); setSelectedStock(null); setSelectedPartner(null); };
  const submitJob = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault(); const f = new FormData(e.currentTarget); const partnerId = Number(f.get("partnerId")) || undefined; const partner = partners.find((p) => p.id === partnerId);
    const job: Job = { id: `DL-${today().slice(2).replaceAll("-", "")}-${String(jobs.length + 1).padStart(3, "0")}`, patient: String(f.get("patient")), clinic: partner ? `${partner.doctor} · ${partner.clinic}` : String(f.get("clinic")) || "Pengirim umum", partnerId, workName: String(f.get("workName")), workCategory: String(f.get("workCategory")), teeth: String(f.get("teeth")), tech: String(f.get("tech")), assistant: String(f.get("assistant")), courier: String(f.get("courier")), feeTech: Number(f.get("feeTech")) || 0, feeAssistant: Number(f.get("feeAssistant")) || 0, feeCourier: Number(f.get("feeCourier")) || 0, status: "Model", due: String(f.get("due")), price: Number(f.get("price")) || 0, paid: 0, paymentStatus: "Pending" };
    save("jobs", [job, ...jobs]); close(); setActive("Pekerjaan");
  };
  const advance = (job: Job) => { const stages = ["Model", "Produksi", "Finishing", "QC", "Selesai"]; const next = stages[Math.min(stages.indexOf(job.status) + 1, 4)]; if (next === "Selesai") { setSelectedJob(job); setModal("complete"); } else if (confirm(`Lanjutkan ${job.id} ke ${next}?`)) save("jobs", jobs.map((x) => x.id === job.id ? { ...x, status: next } : x)); };
  const payment = async (job: Job) => { const remaining = Math.max(0, job.price - job.paid); if (!remaining) return; const value = prompt(`Masukkan pembayaran untuk ${job.id}\nSisa tagihan ${rp(remaining)}`, String(remaining)); if (value === null) return; const amount = Number(value); if (!amount || amount < 0) return alert("Nominal pembayaran tidak valid."); try { apply(await request({ action: "payment", jobId: job.id, amount })); } catch (e) { alert((e as Error).message); } };
  const editFees = (job: Job) => { const a = prompt(`Fee Teknisi ${job.tech}`, String(job.feeTech)); if (a === null) return; const b = prompt(`Fee Asisten ${job.assistant || "-"}`, String(job.feeAssistant)); if (b === null) return; const c = prompt(`Fee Kurir ${job.courier || "-"}`, String(job.feeCourier)); if (c === null) return; save("jobs", jobs.map((x) => x.id === job.id ? { ...x, feeTech: Number(a) || 0, feeAssistant: Number(b) || 0, feeCourier: Number(c) || 0 } : x)); };

  const submitStock = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); const record: Stock = { id: selectedStock?.id || id(stocks), sku: String(f.get("sku")), name: String(f.get("name")), unit: String(f.get("unit")), qty: Number(f.get("qty")), min: Number(f.get("min")), cost: Number(f.get("cost")) }; let nextMoves = moves; if (selectedStock && selectedStock.qty !== record.qty) nextMoves = [{ id: id(moves), stock: record.id, type: "Stok Opname", qty: record.qty, previousQty: selectedStock.qty, date: today(), note: "Koreksi melalui edit bahan" }, ...moves]; save("stocks", selectedStock ? stocks.map((s) => s.id === record.id ? record : s) : [record, ...stocks]); if (nextMoves !== moves) save("moves", nextMoves); close(); };
  const deleteStock = (stock: Stock) => { if (!confirm(`Hapus bahan ${stock.name} beserta histori pergerakannya?`)) return; save("stocks", stocks.filter((s) => s.id !== stock.id)); save("moves", moves.filter((m) => m.stock !== stock.id)); };
  const submitMove = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget), stockId = Number(f.get("stock")), type = String(f.get("type")) as Move["type"], qty = Number(f.get("qty")), old = stocks.find((s) => s.id === stockId)?.qty || 0; const movement: Move = { id: id(moves), stock: stockId, type, qty, previousQty: old, date: String(f.get("date")), note: String(f.get("note")) }; save("stocks", stocks.map((s) => s.id === stockId ? { ...s, qty: type === "Masuk" ? s.qty + qty : type === "Keluar" ? Math.max(0, s.qty - qty) : qty } : s)); save("moves", [movement, ...moves]); close(); };
  const adjustMove = (move: Move) => { const value = prompt(`Ubah jumlah ${move.type}`, String(move.qty)); if (value === null) return; const qty = Number(value); if (qty < 0 || Number.isNaN(qty)) return alert("Jumlah tidak valid."); const delta = qty - move.qty; save("stocks", stocks.map((s) => s.id === move.stock ? { ...s, qty: Math.max(0, move.type === "Keluar" ? s.qty - delta : s.qty + delta) } : s)); save("moves", moves.map((m) => m.id === move.id ? { ...m, qty } : m)); };
  const deleteMove = (move: Move) => { if (!confirm("Hapus pergerakan ini dan kembalikan stok?")) return; save("stocks", stocks.map((s) => s.id === move.stock ? { ...s, qty: Math.max(0, move.type === "Masuk" ? s.qty - move.qty : move.type === "Keluar" ? s.qty + move.qty : s.qty + (move.previousQty ?? move.qty) - move.qty) } : s)); save("moves", moves.filter((m) => m.id !== move.id)); };

  const submitPartner = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); const record: Partner = { id: selectedPartner?.id || id(partners), doctor: String(f.get("doctor")), clinic: String(f.get("clinic")), phone: String(f.get("phone")), email: String(f.get("email")), rewardPoints: selectedPartner?.rewardPoints || 0, lastReward: selectedPartner?.lastReward || "", promo: selectedPartner?.promo || "", promoAt: selectedPartner?.promoAt || "", active: true }; save("partners", selectedPartner ? partners.map((p) => p.id === record.id ? record : p) : [record, ...partners]); close(); };
  const submitCash = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); save("cash", [{ id: id(cash), type: String(f.get("type")) as Cash["type"], category: String(f.get("category")), amount: Number(f.get("amount")), date: String(f.get("date")), note: String(f.get("note")) }, ...cash]); close(); };
  const submitBrand = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget), file = f.get("logo") as File; let logo = brand.logo; if (file?.size) { if (file.size > 1_000_000) return alert("Logo maksimal 1 MB."); logo = await fileData(file); } save("brand", { name: String(f.get("name")), subtitle: String(f.get("subtitle")), logo }); alert("Identitas laboratorium disimpan."); };
  const submitUser = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); try { apply(await request({ action: "createUser", name: f.get("name"), role: f.get("role"), username: f.get("username"), password: f.get("password") })); close(); } catch (err) { alert((err as Error).message); } };
  const resetPassword = async (user: User) => { const password = prompt(`Password baru untuk @${user.username} (minimal 8 karakter)`); if (password === null) return; try { await request({ action: "resetPassword", userId: user.id, password }); alert("Password berhasil diperbarui."); } catch (e) { alert((e as Error).message); } };
  const toggleUser = async (user: User) => { try { apply(await request({ action: "toggleUser", userId: user.id, active: !user.active })); } catch (e) { alert((e as Error).message); } };
  const deleteUser = async (user: User) => { if (!confirm(`Hapus akun ${user.name}?`)) return; try { apply(await request({ action: "deleteUser", userId: user.id })); } catch (e) { alert((e as Error).message); } };

  return <main className="app-shell">
    <aside className="sidebar">
      <BrandIdentity brand={brand} sidebar />
      <nav>{visibleMenus.map((menu) => { const index = menus.indexOf(menu); return <button key={menu} className={active === menu ? "active" : ""} onClick={() => setActive(menu)}><span className="nav-icon">{icons[index]}</span>{menu}{menu === "Stok Bahan" && low.length > 0 && <em>{low.length}</em>}</button>; })}</nav>
      <div className="side-card"><span>●</span><div><b>Akses {me.role}</b><small>{owner ? "Laporan & kontrol penuh" : manager ? "Operasional tanpa laba" : "Pekerjaan & fee pribadi"}</small></div></div>
      <button className="profile" onClick={logout}><span>{me.name.slice(0, 2).toUpperCase()}</span><div><b>{me.name}</b><small>@{me.username} · Keluar</small></div></button>
    </aside>
    <section className="workspace">
      <header className="topbar"><label className="search">⌕<input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Cari order, pasien, dokter, atau klinik..." /></label><div className="account-current"><span>{me.name.slice(0, 2).toUpperCase()}</span><div><b>{me.name}</b><small>{me.role}</small></div></div>{manager && workers.some((u) => u.role === "Teknisi") && <button className="primary" onClick={() => setModal("job")}>＋ Pekerjaan Baru</button>}<button className="logout-btn" onClick={logout}>Keluar</button></header>
      <div className="content">
        <div className="heading"><div><p className="eyebrow">{me.role.toUpperCase()} WORKSPACE · {today()}</p><h1>{active}</h1><p>{owner ? "Pantau operasional, laba, piutang, stok, dan kinerja tim dalam satu ruang kerja." : manager ? "Kelola pekerjaan dan operasional tanpa akses laporan laba laboratorium." : "Perbarui progres pekerjaan dan lihat fee Anda."}</p></div><span className="system-live">● Sesi server aktif</span></div>

        {active === "Dashboard" && <Dashboard me={me} owner={owner} manager={manager} jobs={list} low={low} income={income} expense={expense} fee={feeTotal} openJob={() => setModal("job")} />}

        {active === "Pekerjaan" && <><Workflow /><section className="panel page"><Toolbar title={`${list.length} pekerjaan`} sub={manager ? "Progres, tim, fee, dan status pembayaran" : "Pekerjaan yang ditugaskan kepada Anda"} button={manager && workers.some((u) => u.role === "Teknisi") ? "＋ Pekerjaan Baru" : undefined} click={() => setModal("job")} /><JobTable jobs={list} hideMoney={!manager} actions={(job) => <div className="row-actions">{job.status !== "Selesai" ? <button className="progress-btn" onClick={() => advance(job)}>Lanjutkan →</button> : <span className="completed-mark">✓ Selesai</span>}{manager && <><button onClick={() => editFees(job)}>Fee</button><button onClick={() => { const value = prompt("Harga pekerjaan", String(job.price)); if (value !== null) save("jobs", jobs.map((x) => x.id === job.id ? { ...x, price: Number(value), paymentStatus: x.paid >= Number(value) ? "Lunas" : x.paid > 0 ? "DP" : "Pending" } : x)); }}>Harga</button>{job.paymentStatus !== "Lunas" && <button className="payment-btn" onClick={() => payment(job)}>{job.paid ? "Tambah Bayar" : "Catat DP"}</button>}{owner && <button className="danger" onClick={() => confirm(`Hapus ${job.id}?`) && save("jobs", jobs.filter((x) => x.id !== job.id))}>Hapus</button>}</>}</div>} /></section></>}

        {active === "Dokter & Klinik" && manager && <PartnerPage partners={partners} jobs={jobs} add={() => { setSelectedPartner(null); setModal("partner"); }} edit={(p) => { setSelectedPartner(p); setModal("partner"); }} update={(next) => save("partners", next)} />}

        {active === "Stok Bahan" && manager && <><Toolbar title="Persediaan bahan habis pakai" sub={`Nilai stok ${rp(stocks.reduce((s, x) => s + x.qty * x.cost, 0))}`} button="＋ Tambah Bahan" click={() => { setSelectedStock(null); setModal("stock"); }} />{stocks.length === 0 ? <Empty title="Belum ada bahan" text="Tambahkan bahan pertama untuk memulai persediaan." /> : <div className="stock-grid">{stocks.map((stock) => <article className={`material ${stock.qty <= stock.min ? "critical" : ""}`} key={stock.id}><div><small>{stock.sku}</small><em>{stock.qty <= stock.min ? "KRITIS" : "AMAN"}</em></div><h3>{stock.name}</h3><strong>{stock.qty} <small>{stock.unit}</small></strong><p>Minimum {stock.min} · {rp(stock.cost)}/{stock.unit}</p><div className="material-actions"><button onClick={() => { const value = prompt("Jumlah stok fisik", String(stock.qty)); if (value !== null) { const qty = Number(value); save("stocks", stocks.map((s) => s.id === stock.id ? { ...s, qty } : s)); save("moves", [{ id: id(moves), stock: stock.id, type: "Stok Opname", qty, previousQty: stock.qty, date: today(), note: "Koreksi stok opname" }, ...moves]); } }}>Stok opname</button><button onClick={() => { setSelectedStock(stock); setModal("stock"); }}>Edit</button><button className="danger" onClick={() => deleteStock(stock)}>Hapus</button></div></article>)}</div>}</>}

        {active === "Barang Masuk/Keluar" && manager && <section className="panel page"><Toolbar title="Kartu stok" sub="Barang masuk, pemakaian, dan koreksi opname" button="＋ Catat Pergerakan" click={() => setModal("move")} /><div className="table-wrap"><table><thead><tr><th>TANGGAL</th><th>BAHAN</th><th>JENIS</th><th>JUMLAH</th><th>KETERANGAN</th><th>AKSI</th></tr></thead><tbody>{moves.map((move) => <tr key={move.id}><td>{move.date}</td><td>{stocks.find((s) => s.id === move.stock)?.name || "Bahan dihapus"}</td><td><span className={`payment ${move.type === "Stok Opname" ? "pay-dp" : ""}`}>{move.type}</span></td><td><b>{move.qty}</b></td><td>{move.note}</td><td><div className="row-actions"><button onClick={() => adjustMove(move)}>Edit</button><button className="danger" onClick={() => deleteMove(move)}>Hapus</button></div></td></tr>)}</tbody></table></div>{moves.length === 0 && <Empty title="Belum ada pergerakan" text="Catat barang masuk, pemakaian, atau stok opname." />}</section>}

        {active === "Keuangan" && owner && <Finance cash={cash} jobs={jobs} income={income} expense={expense} fee={feeTotal} add={() => setModal("cash")} remove={(entry) => confirm("Hapus transaksi ini?") && save("cash", cash.filter((x) => x.id !== entry.id))} />}

        {active === "Fee Tim" && <FeePage users={users} me={me} owner={owner} manager={manager} jobs={done} extras={extras} add={() => setModal("bonus")} remove={(entry) => owner && confirm("Hapus fee tambahan ini?") && save("extras", extras.filter((x) => x.id !== entry.id))} />}

        {active === "Akun & Akses" && manager && <AccountPage users={users} me={me} add={() => setModal("user")} reset={resetPassword} toggle={toggleUser} remove={deleteUser} />}

        {active === "Pengaturan Lab" && manager && <BrandSettings brand={brand} submit={submitBrand} remove={() => save("brand", { ...brand, logo: "" })} />}

        {active === "Laporan" && owner && <Reports jobs={jobs} stocks={stocks} income={income} expense={expense} fee={feeTotal} />}
      </div>
    </section>

    {modal && <div className="modal-backdrop" onMouseDown={close}><section className="modal job-modal" onMouseDown={(e) => e.stopPropagation()}><button className="close" onClick={close}>×</button>{modal === "job" && <JobForm users={users} partners={partners} submit={submitJob} />}{modal === "complete" && selectedJob && <Complete job={selectedJob} confirm={() => { save("jobs", jobs.map((x) => x.id === selectedJob.id ? { ...x, status: "Selesai" } : x)); close(); }} />}{modal === "stock" && <StockForm stock={selectedStock} submit={submitStock} />}{modal === "move" && <MoveForm stocks={stocks} submit={submitMove} />}{modal === "partner" && <PartnerForm partner={selectedPartner} submit={submitPartner} />}{modal === "cash" && <CashForm submit={submitCash} />}{modal === "user" && <UserForm owner={owner} submit={submitUser} />}{modal === "bonus" && <BonusForm users={users} submit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); save("extras", [{ id: id(extras), tech: String(f.get("tech")), amount: Number(f.get("amount")), note: String(f.get("note")), date: today() }, ...extras]); close(); }} />}</section></div>}
  </main>;
}

function BrandIdentity({ brand, sidebar = false }: { brand: Brand; sidebar?: boolean }) { return <div className={sidebar ? "brand" : "auth-brand"}>{brand.logo ? <Image className={sidebar ? "brand-mark brand-image" : ""} src={brand.logo} alt={brand.name} width={sidebar ? 40 : 46} height={sidebar ? 40 : 46} unoptimized /> : <span className={sidebar ? "brand-mark" : ""}>{brand.name.slice(0, 2).toUpperCase()}</span>}<div><b>{brand.name}</b><small>{brand.subtitle}</small></div></div>; }
function AuthLoading({ brand }: { brand: Brand }) { return <main className="auth-shell"><section className="auth-card auth-loading"><BrandIdentity brand={brand} /><div className="auth-loader" /><p>Menghubungkan ke database laboratorium…</p></section></main>; }
function Login({ brand, error, submit }: { brand: Brand; error: string; submit: (e: FormEvent<HTMLFormElement>) => void }) { return <main className="auth-shell"><aside className="auth-story"><span>SESI AMAN LINTAS PERANGKAT</span><h1>Satu data laboratorium untuk seluruh tim.</h1><p>Masuk dari komputer atau ponsel mana pun menggunakan akun yang diberikan Owner.</p><div><b>✓</b> Data tersimpan di server</div><div><b>✓</b> Akses berdasarkan peran</div><div><b>✓</b> Sesi login 30 hari</div></aside><section className="auth-card"><BrandIdentity brand={brand} /><p className="eyebrow">LOGIN PENGGUNA</p><h2>Masuk ke DentaLab</h2><form onSubmit={submit}><Field label="Username"><input name="username" autoComplete="username" required autoFocus /></Field><Field label="Password"><input type="password" name="password" autoComplete="current-password" required /></Field>{error && <div className="auth-error">{error}</div>}<button className="primary save">Masuk ke aplikasi</button></form></section></main>; }
function OwnerSetup({ brand, error, submit }: { brand: Brand; error: string; submit: (e: FormEvent<HTMLFormElement>) => void }) { return <main className="auth-shell"><aside className="auth-story"><span>AKTIVASI DATABASE</span><h1>Buat Owner pertama untuk laboratorium.</h1><p>Data ini tersimpan di server dan dapat digunakan lintas perangkat. Owner pertama dapat menambahkan satu Owner kedua.</p></aside><section className="auth-card setup-owner"><BrandIdentity brand={brand} /><h2>Aktifkan sistem</h2><form onSubmit={submit}><Field label="Nama laboratorium"><input name="labName" defaultValue={brand.name} required /></Field><Field label="Nama lengkap Owner"><input name="name" required /></Field><Field label="Username Owner"><input name="username" minLength={4} required /></Field><Field label="Password Owner"><input type="password" name="password" minLength={8} required /></Field>{error && <div className="auth-error">{error}</div>}<button className="primary save">Aktifkan database</button></form></section></main>; }

function Head({ title, sub }: { title: string; sub: string }) { return <div className="panel-head"><div><h2>{title}</h2><p>{sub}</p></div></div>; }
function Toolbar({ title, sub, button, click }: { title: string; sub: string; button?: string; click?: () => void }) { return <div className="toolbar"><div><b>{title}</b><span>{sub}</span></div>{button && <button className="primary" onClick={click}>{button}</button>}</div>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className="empty-state"><span>◇</span><b>{title}</b><p>{text}</p></div>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label>{label}{children}</label>; }
function Workflow() { return <section className="workflow-strip strong-flow"><div className="stage-model"><span>1</span><b>MODEL</b></div><i>→</i><div className="stage-production"><span>2</span><b>PRODUKSI</b></div><i>→</i><div className="stage-finishing"><span>3</span><b>FINISHING</b></div><i>→</i><div className="stage-qc"><span>4</span><b>QUALITY CONTROL</b></div><i>→</i><div className="finish"><span>✓</span><b>SELESAI & FEE</b></div></section>; }

function Dashboard({ me, owner, manager, jobs, low, income, expense, fee, openJob }: { me: User; owner: boolean; manager: boolean; jobs: Job[]; low: Stock[]; income: number; expense: number; fee: number; openJob: () => void }) { return <><section className="dashboard-hero"><div><span>{owner ? "OWNER CONTROL CENTER" : manager ? "OPERASIONAL LAB" : "RUANG KERJA PRIBADI"}</span><h2>Selamat datang, {me.name}</h2><p>{owner ? "Semua indikator penting terbaca cepat, termasuk laba dan laporan keuangan." : "Fokus pada pekerjaan, progres, dan aktivitas operasional hari ini."}</p></div><div className="hero-score"><strong>{jobs.filter((j) => j.status !== "Selesai").length}</strong><span>Pekerjaan aktif</span></div></section><div className="metrics">{[["◈", jobs.filter((j) => j.status !== "Selesai").length, "Pekerjaan aktif"], ["✓", jobs.filter((j) => j.status === "Selesai").length, "Selesai"], ["▣", low.length, "Stok kritis"], ...(owner ? [["Rp", rp(income - expense - fee), "Laba operasional"]] : [])].map((x, i) => <article key={String(x[2])}><span className={["mint", "blue", "orange", "violet"][i]}>{x[0]}</span><strong>{x[1]}</strong><p>{x[2]}</p><small>Data server terbaru</small></article>)}</div><div className="main-grid"><section className="panel jobs-panel"><Head title="Pekerjaan berjalan" sub="Prioritas berdasarkan tenggat" /><JobTable jobs={jobs.slice(0, 6)} hideMoney={!manager} /></section><aside className="right-stack"><section className="panel"><Head title="Stok kritis" sub="Perlu segera ditindaklanjuti" />{manager ? low.length ? low.map((x) => <div className="stock-row" key={x.id}><span className="stock-icon red">▣</span><div><b>{x.name}</b><small>Minimum {x.min} {x.unit}</small></div><strong>{x.qty} {x.unit}</strong></div>) : <div className="mini-empty">Tidak ada stok kritis</div> : <div className="mini-empty">Dikelola Owner/Admin</div>}</section>{owner && <section className="panel cash-mini"><Head title="Keuangan bulan ini" sub="Hanya dapat dilihat Owner" /><p><span>Pendapatan</span><b>{rp(income)}</b></p><p><span>Pengeluaran</span><b>{rp(expense)}</b></p><p><span>Fee tim</span><b>{rp(fee)}</b></p><p className="profit"><span>Laba operasional</span><b>{rp(income - expense - fee)}</b></p></section>}</aside></div>{manager && jobs.length === 0 && <button className="primary save" onClick={openJob}>Mulai catat pekerjaan pertama</button>}</>; }

function JobTable({ jobs, hideMoney, actions }: { jobs: Job[]; hideMoney?: boolean; actions?: (j: Job) => ReactNode }) { return <div className="table-wrap"><table><thead><tr><th>ORDER & PASIEN</th><th>PEKERJAAN</th><th>TIM & FEE</th><th>PROGRES</th>{!hideMoney && <th>PEMBAYARAN</th>}{actions && <th>AKSI</th>}</tr></thead><tbody>{jobs.map((j) => <tr key={j.id}><td><b>{j.id}</b><span>{j.patient} · {j.clinic}</span></td><td><b>{j.workName}</b><span>{j.workCategory} · Gigi {j.teeth || "-"} · {j.due}</span></td><td><div className="team-stack"><span><b>T</b>{j.tech} · {rp(j.feeTech)}</span>{j.assistant && <span><b>A</b>{j.assistant} · {rp(j.feeAssistant)}</span>}{j.courier && <span><b>K</b>{j.courier} · {rp(j.feeCourier)}</span>}</div></td><td><span className={`status s-${j.status.toLowerCase()}`}>{j.status}</span></td>{!hideMoney && <td><b>{rp(j.price - j.paid)}</b><span className={`payment pay-${(j.paymentStatus || (j.paid ? "DP" : "Pending")).toLowerCase()}`}>{j.paymentStatus || (j.paid ? "DP" : "Pending")}</span><span>Terbayar {rp(j.paid)} dari {rp(j.price)}</span></td>}{actions && <td>{actions(j)}</td>}</tr>)}</tbody></table>{jobs.length === 0 && <Empty title="Belum ada pekerjaan" text="Catat pekerjaan pertama untuk memulai alur laboratorium." />}</div>; }

function PartnerPage({ partners, jobs, add, edit, update }: { partners: Partner[]; jobs: Job[]; add: () => void; edit: (p: Partner) => void; update: (p: Partner[]) => void }) { return <section className="panel page"><Toolbar title="Database dokter & klinik" sub="Kontak, histori order, reward, dan penanda promo" button="＋ Tambah Pengirim" click={add} />{partners.length === 0 ? <Empty title="Belum ada dokter atau klinik" text="Tambahkan pengirim pertama agar dapat dipilih pada pekerjaan." /> : <div className="table-wrap"><table><thead><tr><th>DOKTER / KLINIK</th><th>KONTAK</th><th>HISTORI</th><th>REWARD</th><th>PROMO</th><th>AKSI</th></tr></thead><tbody>{partners.map((p) => { const orders = jobs.filter((j) => j.partnerId === p.id); return <tr key={p.id}><td><b>{p.doctor}</b><span>{p.clinic}</span></td><td><a className="wa-link" href={`https://wa.me/${p.phone.replace(/\D/g, "").replace(/^0/, "62")}`} target="_blank" rel="noreferrer">{p.phone}</a><span>{p.email}</span></td><td><b>{orders.length} pekerjaan</b><span>{rp(orders.reduce((s, j) => s + j.price, 0))}</span></td><td><b>{p.rewardPoints} poin</b><span>{p.lastReward || "Belum ada"}</span></td><td>{p.promo ? <span className="promo-badge">✓ {p.promo}<small>{p.promoAt}</small></span> : <span className="no-promo">Belum ada promo</span>}</td><td><div className="row-actions"><button onClick={() => { const value = prompt("Tambahkan poin reward", "1"); if (value !== null) update(partners.map((x) => x.id === p.id ? { ...x, rewardPoints: x.rewardPoints + (Number(value) || 0), lastReward: today() } : x)); }}>Reward</button><button onClick={() => { const value = prompt("Nama promo", p.promo || "Promo loyalitas"); if (value !== null) update(partners.map((x) => x.id === p.id ? { ...x, promo: value, promoAt: value ? today() : "" } : x)); }}>Promo</button><button onClick={() => edit(p)}>Edit</button><button className="danger" onClick={() => confirm(`Hapus ${p.doctor}?`) && update(partners.filter((x) => x.id !== p.id))}>Hapus</button></div></td></tr>; })}</tbody></table></div>}</section>; }

function Finance({ cash, jobs, income, expense, fee, add, remove }: { cash: Cash[]; jobs: Job[]; income: number; expense: number; fee: number; add: () => void; remove: (c: Cash) => void }) { const counts = { Pending: jobs.filter((j) => (j.paymentStatus || "Pending") === "Pending").length, DP: jobs.filter((j) => j.paymentStatus === "DP").length, Lunas: jobs.filter((j) => j.paymentStatus === "Lunas").length }; return <><div className="metrics three"><article><span className="mint">↓</span><strong>{rp(income)}</strong><p>Pemasukan</p></article><article><span className="orange">↑</span><strong>{rp(expense)}</strong><p>Pengeluaran</p></article><article><span className="violet">=</span><strong>{rp(income - expense - fee)}</strong><p>Laba setelah fee</p></article></div><section className="payment-summary"><article className="pay-pending"><b>{counts.Pending}</b><span>Pending</span></article><article className="pay-dp"><b>{counts.DP}</b><span>DP / belum lunas</span></article><article className="pay-lunas"><b>{counts.Lunas}</b><span>Lunas</span></article><article><b>{rp(jobs.reduce((s, j) => s + Math.max(0, j.price - j.paid), 0))}</b><span>Total piutang</span></article></section><section className="panel page"><Toolbar title="Buku kas laboratorium" sub="Rahasia—hanya dua akun Owner yang dapat membuka" button="＋ Transaksi" click={add} /><div className="table-wrap"><table><thead><tr><th>TANGGAL</th><th>TIPE</th><th>KATEGORI</th><th>KETERANGAN</th><th>NOMINAL</th><th>AKSI</th></tr></thead><tbody>{cash.map((c) => <tr key={c.id}><td>{c.date}</td><td>{c.type}</td><td>{c.category}</td><td>{c.note}</td><td><b>{rp(c.amount)}</b></td><td><button className="text-danger" onClick={() => remove(c)}>Hapus</button></td></tr>)}</tbody></table></div></section></>; }

function FeePage({ users, me, owner, manager, jobs, extras, add, remove }: { users: User[]; me: User; owner: boolean; manager: boolean; jobs: Job[]; extras: Extra[]; add: () => void; remove: (e: Extra) => void }) { const visible = users.filter((u) => roles.includes(u.role) && (manager || u.id === me.id)); const assigned = (u: User, j: Job) => u.role === "Teknisi" ? j.tech === u.name : u.role === "Asisten Teknisi" ? j.assistant === u.name : j.courier === u.name; const fee = (u: User, j: Job) => u.role === "Teknisi" ? j.feeTech : u.role === "Asisten Teknisi" ? j.feeAssistant : j.feeCourier; return <><Toolbar title="Fee tim" sub="Fee otomatis setelah pekerjaan selesai" button={manager && visible.length ? "＋ Fee Tambahan" : undefined} click={add} /><div className="bonus-grid">{visible.map((u) => { const completed = jobs.filter((j) => assigned(u, j)), automatic = completed.reduce((s, j) => s + fee(u, j), 0), extra = extras.filter((x) => x.tech === u.name).reduce((s, x) => s + x.amount, 0); return <article className="panel tech bonus-detail" key={u.id}><span>{u.name.slice(0, 2).toUpperCase()}</span><div><small>{u.role.toUpperCase()}</small><h3>{u.name}</h3><p>{completed.length} pekerjaan selesai · Tambahan {rp(extra)}</p></div><strong>{rp(automatic + extra)}</strong></article>; })}</div>{manager && extras.length > 0 && <section className="panel extra-list"><Head title="Riwayat fee tambahan" sub="Penyesuaian oleh Owner/Admin" />{extras.map((x) => <p key={x.id}><span><b>{x.tech}</b><small>{x.date} · {x.note}</small></span><strong>{rp(x.amount)}</strong>{owner && <button onClick={() => remove(x)}>Hapus</button>}</p>)}</section>}</>; }

function AccountPage({ users, me, add, reset, toggle, remove }: { users: User[]; me: User; add: () => void; reset: (u: User) => void; toggle: (u: User) => void; remove: (u: User) => void }) { const ownerCount = users.filter((u) => u.role === "Owner").length; return <section className="panel page"><Toolbar title={`Akun pengguna · ${ownerCount}/2 Owner`} sub="Akun dan sesi tersimpan aman di server" button="＋ Tambah Akun" click={add} /><div className="access-note"><b>Pembatasan data</b><p>Owner dapat melihat laba dan laporan. Admin mengelola operasional tanpa angka laba. Teknisi, Asisten, dan Kurir hanya melihat tugas serta fee sendiri.</p></div><div className="table-wrap"><table><thead><tr><th>NAMA & USERNAME</th><th>PERAN</th><th>AKSES</th><th>STATUS</th><th>AKSI</th></tr></thead><tbody>{users.map((u) => <tr key={u.id}><td><b>{u.name}</b><span>@{u.username}</span></td><td><span className={`role role-${u.role.toLowerCase().replaceAll(" ", "-")}`}>{u.role}</span></td><td>{u.role === "Owner" ? "Laporan, laba & seluruh data" : u.role === "Admin" ? "Operasional tanpa keuangan" : "Pekerjaan & fee sendiri"}</td><td>{u.active ? "Aktif" : "Nonaktif"}</td><td><div className="row-actions">{(me.role === "Owner" || u.role !== "Owner") && <button onClick={() => reset(u)}>Reset Password</button>}{u.role !== "Owner" && <><button onClick={() => toggle(u)}>{u.active ? "Nonaktifkan" : "Aktifkan"}</button><button className="danger" onClick={() => remove(u)}>Hapus</button></>}</div></td></tr>)}</tbody></table></div></section>; }

function BrandSettings({ brand, submit, remove }: { brand: Brand; submit: (e: FormEvent<HTMLFormElement>) => void; remove: () => void }) { return <div className="settings-grid"><section className="panel brand-preview"><p className="eyebrow">PRATINJAU IDENTITAS</p>{brand.logo ? <Image src={brand.logo} alt={brand.name} width={94} height={94} unoptimized /> : <span>{brand.name.slice(0, 2).toUpperCase()}</span>}<h2>{brand.name}</h2><p>{brand.subtitle}</p></section><section className="panel brand-form"><Head title="Nama & logo laboratorium" sub="Dapat diubah Owner atau Admin" /><form onSubmit={submit}><Field label="Nama laboratorium"><input name="name" defaultValue={brand.name} required /></Field><Field label="Keterangan singkat"><input name="subtitle" defaultValue={brand.subtitle} required /></Field><Field label="Logo (maksimal 1 MB)"><input type="file" name="logo" accept="image/png,image/jpeg,image/webp" /></Field><div className="brand-actions"><button className="primary">Simpan</button>{brand.logo && <button type="button" className="secondary" onClick={remove}>Hapus logo</button>}</div></form></section></div>; }

function Reports({ jobs, stocks, income, expense, fee }: { jobs: Job[]; stocks: Stock[]; income: number; expense: number; fee: number }) { const status = (s: PaymentStatus) => jobs.filter((j) => (j.paymentStatus || "Pending") === s); return <><section className="report"><div><p className="eyebrow">LAPORAN RAHASIA OWNER</p><h2>Kinerja Laboratorium</h2><p>Operasional, piutang, pembayaran, dan laba.</p></div><button onClick={() => window.print()}>Cetak / Simpan PDF</button></section><div className="report-grid"><Report title="Pekerjaan & pembayaran" rows={[["Total order", jobs.length], ["Pending", status("Pending").length], ["DP", status("DP").length], ["Lunas", status("Lunas").length], ["Piutang", rp(jobs.reduce((s, j) => s + j.price - j.paid, 0))]]} /><Report title="Keuangan" rows={[["Pendapatan", rp(income)], ["Pengeluaran", rp(expense)], ["Fee tim", rp(fee)], ["Laba", rp(income - expense - fee)]]} /><Report title="Persediaan" rows={[["Jenis bahan", stocks.length], ["Stok kritis", stocks.filter((s) => s.qty <= s.min).length], ["Nilai stok", rp(stocks.reduce((s, x) => s + x.qty * x.cost, 0))]]} /></div></>; }
function Report({ title, rows }: { title: string; rows: (string | number)[][] }) { return <article className="panel report-card"><h3>{title}</h3>{rows.map((x, i) => <p key={i}><span>{x[0]}</span><b>{x[1]}</b></p>)}</article>; }

function JobForm({ users, partners, submit }: { users: User[]; partners: Partner[]; submit: (e: FormEvent<HTMLFormElement>) => void }) { return <><p className="eyebrow">ORDER BARU · TIM, FEE & TAGIHAN</p><h2>Catat pekerjaan masuk</h2><div className="form-flow"><b>Model</b><i>→</i><span>Produksi</span><i>→</i><span>Finishing</span><i>→</i><span>QC</span><i>→</i><span>Selesai</span></div><form onSubmit={submit}><div className="form-section"><h3>Informasi pekerjaan</h3><div className="form-grid"><Field label="Nama pasien"><input name="patient" required /></Field><Field label="Dokter / klinik"><select name="partnerId"><option value="0">Pengirim manual</option>{partners.filter((p) => p.active).map((p) => <option value={p.id} key={p.id}>{p.doctor} · {p.clinic}</option>)}</select></Field><Field label="Pengirim manual"><input name="clinic" placeholder="Dokter / klinik" /></Field><Field label="Jenis pekerjaan"><input name="workName" required placeholder="Valplast, crown zirconia, dll." /></Field><Field label="Kategori"><select name="workCategory"><option>Gigi Palsu Lepasan</option><option>Crown & Bridge</option><option>Implan</option><option>Orthodonti</option><option>Repair</option><option>Lainnya</option></select></Field><Field label="Nomor gigi / rahang"><input name="teeth" /></Field><Field label="Target selesai"><input type="date" name="due" required /></Field></div></div><div className="form-section fee-section"><h3>Tim produksi & fee</h3><div className="form-grid"><Field label="Teknisi"><select name="tech" required>{users.filter((u) => u.role === "Teknisi" && u.active).map((u) => <option key={u.id}>{u.name}</option>)}</select></Field><Field label="Fee Teknisi"><input type="number" min="0" name="feeTech" required /></Field><Field label="Asisten (opsional)"><select name="assistant"><option value="">Tanpa asisten</option>{users.filter((u) => u.role === "Asisten Teknisi" && u.active).map((u) => <option key={u.id}>{u.name}</option>)}</select></Field><Field label="Fee Asisten"><input type="number" min="0" name="feeAssistant" /></Field><Field label="Kurir (opsional)"><select name="courier"><option value="">Tanpa kurir</option>{users.filter((u) => u.role === "Kurir" && u.active).map((u) => <option key={u.id}>{u.name}</option>)}</select></Field><Field label="Fee Kurir"><input type="number" min="0" name="feeCourier" /></Field></div></div><div className="form-section price-section"><Field label="Harga pekerjaan"><input type="number" min="0" name="price" required /></Field><p className="payment-hint">Status awal otomatis <b>Pending</b>. Setelah menerima uang, catat sebagai DP hingga berubah menjadi Lunas.</p></div><button className="primary save">Simpan pekerjaan</button></form></>; }

function Complete({ job, confirm }: { job: Job; confirm: () => void }) { return <div className="complete-modal"><span className="complete-icon">✓</span><p className="eyebrow">KONFIRMASI AKHIR</p><h2>Selesaikan pekerjaan?</h2><p><b>{job.workName}</b> · {job.id} akan ditandai selesai dan fee tim masuk perhitungan bulan berjalan.</p><div className="complete-summary fee-confirm"><span><small>Teknisi</small><b>{rp(job.feeTech)}</b></span><span><small>Asisten</small><b>{rp(job.feeAssistant)}</b></span><span><small>Kurir</small><b>{rp(job.feeCourier)}</b></span></div><button className="primary save" onClick={confirm}>✓ Konfirmasi selesai</button></div>; }

function StockForm({ stock, submit }: { stock: Stock | null; submit: (e: FormEvent<HTMLFormElement>) => void }) { return <><p className="eyebrow">MASTER BAHAN</p><h2>{stock ? "Edit bahan" : "Tambah bahan"}</h2><form onSubmit={submit}><div className="form-grid"><Field label="Kode / SKU"><input name="sku" defaultValue={stock?.sku} required /></Field><Field label="Nama bahan"><input name="name" defaultValue={stock?.name} required /></Field><Field label="Satuan"><input name="unit" defaultValue={stock?.unit} required placeholder="box, gram, pcs" /></Field><Field label="Stok fisik"><input type="number" step=".01" min="0" name="qty" defaultValue={stock?.qty} required /></Field><Field label="Batas minimum"><input type="number" step=".01" min="0" name="min" defaultValue={stock?.min} required /></Field><Field label="Harga per satuan"><input type="number" min="0" name="cost" defaultValue={stock?.cost} required /></Field></div><button className="primary save">Simpan bahan</button></form></>; }

function MoveForm({ stocks, submit }: { stocks: Stock[]; submit: (e: FormEvent<HTMLFormElement>) => void }) { return <><p className="eyebrow">KARTU STOK</p><h2>Mutasi & stok opname</h2><form onSubmit={submit}><div className="form-grid"><Field label="Bahan"><select name="stock" required>{stocks.map((s) => <option value={s.id} key={s.id}>{s.name} · {s.qty} {s.unit}</option>)}</select></Field><Field label="Jenis"><select name="type"><option>Masuk</option><option>Keluar</option><option>Stok Opname</option></select></Field><Field label="Jumlah"><input type="number" step=".01" min="0" name="qty" required /></Field><Field label="Tanggal"><input type="date" name="date" defaultValue={today()} required /></Field><Field label="Keterangan"><input name="note" required /></Field></div><button className="primary save">Simpan pergerakan</button></form></>; }

function PartnerForm({ partner, submit }: { partner: Partner | null; submit: (e: FormEvent<HTMLFormElement>) => void }) { return <><p className="eyebrow">DATABASE PENGIRIM</p><h2>{partner ? "Edit dokter & klinik" : "Tambah dokter & klinik"}</h2><form onSubmit={submit}><div className="form-grid"><Field label="Nama dokter"><input name="doctor" defaultValue={partner?.doctor} required /></Field><Field label="Nama klinik"><input name="clinic" defaultValue={partner?.clinic} required /></Field><Field label="Nomor telepon / WhatsApp"><input name="phone" defaultValue={partner?.phone} required /></Field><Field label="Email"><input type="email" name="email" defaultValue={partner?.email} /></Field></div><button className="primary save">Simpan pengirim</button></form></>; }

function CashForm({ submit }: { submit: (e: FormEvent<HTMLFormElement>) => void }) { return <><p className="eyebrow">BUKU KAS OWNER</p><h2>Transaksi baru</h2><form onSubmit={submit}><div className="form-grid"><Field label="Jenis"><select name="type"><option>Masuk</option><option>Keluar</option></select></Field><Field label="Kategori"><input name="category" required /></Field><Field label="Nominal"><input type="number" min="0" name="amount" required /></Field><Field label="Tanggal"><input type="date" name="date" defaultValue={today()} required /></Field><Field label="Keterangan"><input name="note" required /></Field></div><button className="primary save">Simpan transaksi</button></form></>; }

function UserForm({ owner, submit }: { owner: boolean; submit: (e: FormEvent<HTMLFormElement>) => void }) { return <><p className="eyebrow">AKUN SERVER & PASSWORD</p><h2>Tambah pengguna</h2><form onSubmit={submit}><div className="form-grid"><Field label="Nama lengkap"><input name="name" required /></Field><Field label="Peran"><select name="role"><option>Teknisi</option><option>Asisten Teknisi</option><option>Kurir</option><option>Admin</option>{owner && <option>Owner</option>}</select></Field><Field label="Username"><input name="username" minLength={4} autoComplete="off" required /></Field><Field label="Password awal"><input type="password" name="password" minLength={8} autoComplete="new-password" required /></Field></div><div className="access-note"><b>Owner maksimal dua akun</b><p>Hanya Owner yang dapat membuat Owner kedua. Admin tidak dapat mengakses laporan, laba, maupun buku kas.</p></div><button className="primary save">Buat akun</button></form></>; }

function BonusForm({ users, submit }: { users: User[]; submit: (e: FormEvent<HTMLFormElement>) => void }) { return <><p className="eyebrow">FEE TAMBAHAN</p><h2>Tambahan fee pekerja</h2><form onSubmit={submit}><div className="form-grid"><Field label="Pekerja"><select name="tech">{users.filter((u) => roles.includes(u.role) && u.active).map((u) => <option key={u.id}>{u.name}</option>)}</select></Field><Field label="Nominal"><input type="number" min="0" name="amount" required /></Field><Field label="Keterangan"><input name="note" required /></Field></div><button className="primary save">Simpan fee</button></form></>; }
