"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";

type Work={id:number;name:string;category:string;price:number;bonus:number;days:number};
type Job={id:string;patient:string;clinic:string;work:number;teeth:string;tech:string;status:string;due:string;price:number;paid:number};
type Stock={id:number;sku:string;name:string;unit:string;qty:number;min:number;cost:number};
type Move={id:number;stock:number;type:string;qty:number;date:string;note:string};
type Cash={id:number;type:"Masuk"|"Keluar";category:string;amount:number;date:string;note:string};
const works0:Work[]=[{id:1,name:"Crown Zirconia",category:"Crown & Bridge",price:1850000,bonus:150000,days:5},{id:2,name:"PFM Bridge / unit",category:"Crown & Bridge",price:1250000,bonus:110000,days:6},{id:3,name:"Flexible Denture",category:"Denture",price:2750000,bonus:180000,days:7},{id:4,name:"Acrylic Denture",category:"Denture",price:1650000,bonus:130000,days:6},{id:5,name:"E-max Veneer",category:"Estetik",price:2250000,bonus:175000,days:7}];
const jobs0:Job[]=[{id:"DL-260715-028",patient:"Rina Anggraini",clinic:"Klinik Senyum",work:1,teeth:"11, 12",tech:"Andi",status:"Finishing",due:"2026-07-15",price:3700000,paid:2000000},{id:"DL-260715-027",patient:"Budi Santoso",clinic:"drg. Maya",work:3,teeth:"34–37",tech:"Rizal",status:"Produksi",due:"2026-07-16",price:2750000,paid:2750000},{id:"DL-260715-026",patient:"Siska Permata",clinic:"Dentalia",work:2,teeth:"21–23",tech:"Dimas",status:"QC",due:"2026-07-16",price:3750000,paid:0},{id:"DL-260715-025",patient:"Anton Wijaya",clinic:"Klinik Ceria",work:4,teeth:"Full rahang atas",tech:"Andi",status:"Selesai",due:"2026-07-14",price:1650000,paid:1650000}];
const stock0:Stock[]=[{id:1,sku:"ZIR-A2",name:"Zirconia Block A2",unit:"disc",qty:2,min:3,cost:485000},{id:2,sku:"CMS-01",name:"Cold Mould Seal",unit:"botol",qty:1,min:2,cost:98000},{id:3,sku:"ACR-PNK",name:"Acrylic Powder Pink",unit:"kg",qty:3.5,min:2,cost:450000},{id:4,sku:"GLV-M",name:"Nitrile Glove M",unit:"box",qty:8,min:4,cost:72000}];
const cash0:Cash[]=[{id:1,type:"Masuk",category:"Pembayaran pekerjaan",amount:2750000,date:"2026-07-15",note:"DL-260715-027"},{id:2,type:"Keluar",category:"Pembelian bahan",amount:1455000,date:"2026-07-14",note:"Zirconia Block A2 × 3"},{id:3,type:"Masuk",category:"Pelunasan pekerjaan",amount:1650000,date:"2026-07-14",note:"DL-260715-025"}];
const menus=["Dashboard","Pekerjaan","Jenis & Tarif","Stok Bahan","Barang Masuk/Keluar","Keuangan","Bonus Teknisi","Laporan"],icons=["⌂","◈","₠","▣","⇅","◒","★","▤"],rp=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
function stored<T>(key:string,start:T){const[v,setV]=useState(start);useEffect(()=>{const x=localStorage.getItem(key);if(x)setV(JSON.parse(x))},[key]);useEffect(()=>localStorage.setItem(key,JSON.stringify(v)),[key,v]);return[v,setV]as const}

export default function Home(){
 const[active,setActive]=useState("Dashboard"),[search,setSearch]=useState(""),[modal,setModal]=useState(""),[edit,setEdit]=useState<Work|null>(null);
 const[works,setWorks]=stored("dl-works",works0),[jobs,setJobs]=stored("dl-jobs",jobs0),[stocks,setStocks]=stored("dl-stock",stock0),[moves,setMoves]=stored<Move[]>("dl-moves",[]),[cash,setCash]=stored("dl-cash",cash0);
 const income=cash.filter(x=>x.type==="Masuk").reduce((s,x)=>s+x.amount,0),expense=cash.filter(x=>x.type==="Keluar").reduce((s,x)=>s+x.amount,0),done=jobs.filter(j=>j.status==="Selesai"),bonus=done.reduce((s,j)=>s+(works.find(w=>w.id===j.work)?.bonus||0),0),low=stocks.filter(x=>x.qty<=x.min);
 const list=useMemo(()=>jobs.filter(j=>`${j.id} ${j.patient} ${j.clinic}`.toLowerCase().includes(search.toLowerCase())),[jobs,search]);
 const submitWork=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),w={id:edit?.id||Date.now(),name:String(f.get("name")),category:String(f.get("category")),price:Number(f.get("price")),bonus:Number(f.get("bonus")),days:Number(f.get("days"))};setWorks(edit?works.map(x=>x.id===w.id?w:x):[...works,w]);setModal("");setEdit(null)};
 const submitJob=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),wid=Number(f.get("work")),w=works.find(x=>x.id===wid)!;setJobs([{id:`DL-260715-${String(jobs.length+29).padStart(3,"0")}`,patient:String(f.get("patient")),clinic:String(f.get("clinic")),work:wid,teeth:String(f.get("teeth")),tech:String(f.get("tech")),status:"Model",due:String(f.get("due")),price:Number(f.get("price"))||w.price,paid:0},...jobs]);setModal("")};
 const submitMove=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),id=Number(f.get("stock")),type=String(f.get("type")),q=Number(f.get("qty"));setStocks(stocks.map(x=>x.id===id?{...x,qty:type==="Masuk"?x.qty+q:type==="Keluar"?Math.max(0,x.qty-q):q}:x));setMoves([{id:Date.now(),stock:id,type,qty:q,date:String(f.get("date")),note:String(f.get("note"))},...moves]);setModal("")};
 const submitCash=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setCash([{id:Date.now(),type:String(f.get("type"))as Cash["type"],category:String(f.get("category")),amount:Number(f.get("amount")),date:String(f.get("date")),note:String(f.get("note"))},...cash]);setModal("")};
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">DL</span><div><b>DentaLab Pro</b><small>Laboratory ERP</small></div></div><nav>{menus.map((m,i)=><button key={m} className={active===m?"active":""} onClick={()=>setActive(m)}><span className="nav-icon">{icons[i]}</span>{m}{m==="Stok Bahan"&&<em>{low.length}</em>}</button>)}</nav><div className="side-card"><span>●</span><div><b>Sistem operasional aktif</b><small>Data tersimpan otomatis</small></div></div><button className="profile"><span>SA</span><div><b>Siti Aminah</b><small>Administrator</small></div></button></aside><section className="workspace"><header className="topbar"><label className="search">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari order, pasien, atau klinik..."/></label><button className="primary" onClick={()=>setModal("job")}>＋ Pekerjaan Baru</button></header><div className="content"><div className="heading"><div><p className="eyebrow">DENTAL LAB OPERATING SYSTEM</p><h1>{active}</h1><p>Kelola operasional, keuangan, bonus, dan persediaan dalam satu sistem.</p></div><span className="system-live">● Sistem aktif</span></div>
 {active==="Dashboard"&&<><Metrics jobs={jobs} low={low.length} income={income} expense={expense} bonus={bonus}/><div className="main-grid"><section className="panel jobs-panel"><Head title="Pekerjaan berjalan" sub="Prioritas berdasarkan tenggat"/><JobTable jobs={list.slice(0,6)} works={works}/></section><aside className="right-stack"><section className="panel"><Head title="Stok kritis" sub="Perlu segera ditindaklanjuti"/>{low.map(x=><div className="stock-row" key={x.id}><span className="stock-icon red">▣</span><div><b>{x.name}</b><small>Minimum {x.min} {x.unit}</small></div><strong>{x.qty} {x.unit}</strong></div>)}</section><section className="panel cash-mini"><Head title="Keuangan bulan ini" sub="Ringkasan kas berjalan"/><p><span>Pendapatan</span><b>{rp(income)}</b></p><p><span>Pengeluaran</span><b>{rp(expense)}</b></p><p><span>Bonus teknisi</span><b>{rp(bonus)}</b></p><p className="profit"><span>Laba operasional</span><b>{rp(income-expense-bonus)}</b></p></section></aside></div></>}
 {active==="Pekerjaan"&&<section className="panel page"><Toolbar title={`${list.length} pekerjaan`} sub="Ubah status, harga, dan pembayaran setiap order"/><JobTable jobs={list} works={works} action={j=><div className="row-actions"><button onClick={()=>setJobs(jobs.map(x=>x.id===j.id?{...x,status:x.status==="Selesai"?"Produksi":"Selesai"}:x))}>{j.status==="Selesai"?"Buka":"Selesai"}</button><button onClick={()=>{const n=prompt("Harga pekerjaan",String(j.price));if(n)setJobs(jobs.map(x=>x.id===j.id?{...x,price:Number(n)}:x))}}>Harga</button><button onClick={()=>{const n=prompt("Jumlah pembayaran",String(j.price-j.paid));if(n){setJobs(jobs.map(x=>x.id===j.id?{...x,paid:Math.min(x.price,x.paid+Number(n))}:x));setCash([{id:Date.now(),type:"Masuk",category:"Pembayaran pekerjaan",amount:Number(n),date:"2026-07-15",note:j.id},...cash])}}}>Bayar</button></div>}/></section>}
 {active==="Jenis & Tarif"&&<section className="panel page"><Toolbar title="Master jenis pekerjaan" sub="Semua tindakan, tarif, bonus, dan estimasi" button="＋ Jenis Pekerjaan" click={()=>setModal("work")}/><table><thead><tr><th>JENIS PEKERJAAN</th><th>KATEGORI</th><th>TARIF</th><th>BONUS TEKNISI</th><th>ESTIMASI</th><th>AKSI</th></tr></thead><tbody>{works.map(w=><tr key={w.id}><td><b>{w.name}</b></td><td>{w.category}</td><td><b>{rp(w.price)}</b></td><td>{rp(w.bonus)}</td><td>{w.days} hari</td><td><div className="row-actions"><button onClick={()=>{setEdit(w);setModal("work")}}>Edit</button><button onClick={()=>setWorks(works.filter(x=>x.id!==w.id))}>Hapus</button></div></td></tr>)}</tbody></table></section>}
 {active==="Stok Bahan"&&<><Toolbar title="Persediaan bahan habis pakai" sub={`Nilai stok ${rp(stocks.reduce((s,x)=>s+x.qty*x.cost,0))}`} button="＋ Mutasi / Opname" click={()=>setModal("move")}/><div className="stock-grid">{stocks.map(s=><article className={`material ${s.qty<=s.min?"critical":""}`} key={s.id}><div><small>{s.sku}</small><em>{s.qty<=s.min?"KRITIS":"AMAN"}</em></div><h3>{s.name}</h3><strong>{s.qty} <small>{s.unit}</small></strong><p>Minimum {s.min} · {rp(s.cost)}/{s.unit}</p><button onClick={()=>{const n=prompt("Jumlah stok fisik",String(s.qty));if(n!==null)setStocks(stocks.map(x=>x.id===s.id?{...x,qty:Number(n)}:x))}}>Koreksi stok opname</button></article>)}</div></>}
 {active==="Barang Masuk/Keluar"&&<section className="panel page"><Toolbar title="Kartu stok" sub="Barang masuk, pemakaian, dan koreksi opname" button="＋ Catat Pergerakan" click={()=>setModal("move")}/><SimpleTable heads={["TANGGAL","BAHAN","JENIS","JUMLAH","KETERANGAN"]} rows={moves.map(m=>[m.date,stocks.find(s=>s.id===m.stock)?.name||"-",m.type,String(m.qty),m.note])}/></section>}
 {active==="Keuangan"&&<><Metrics jobs={jobs} low={low.length} income={income} expense={expense} bonus={bonus} finance/><section className="panel page"><Toolbar title="Buku kas laboratorium" sub="Pemasukan dan pengeluaran tercatat" button="＋ Transaksi" click={()=>setModal("cash")}/><SimpleTable heads={["TANGGAL","TIPE","KATEGORI","KETERANGAN","NOMINAL"]} rows={cash.map(c=>[c.date,c.type,c.category,c.note,rp(c.amount)])}/></section></>}
 {active==="Bonus Teknisi"&&<div className="bonus-grid">{["Andi","Dimas","Rizal","Lina"].map(t=>{const a=done.filter(j=>j.tech===t),b=a.reduce((s,j)=>s+(works.find(w=>w.id===j.work)?.bonus||0),0);return <article className="panel tech" key={t}><span>{t.slice(0,2).toUpperCase()}</span><div><small>TEKNISI</small><h3>{t}</h3><p>{a.length} pekerjaan selesai</p></div><strong>{rp(b)}</strong></article>})}</div>}
 {active==="Laporan"&&<><section className="report"><div><p className="eyebrow">LAPORAN MANAJEMEN · JULI 2026</p><h2>Kinerja Laboratorium</h2><p>Ringkasan operasional siap cetak.</p></div><button onClick={()=>window.print()}>Cetak / Simpan PDF</button></section><div className="report-grid"><Report title="Operasional" data={[["Total order",jobs.length],["Order selesai",done.length],["Nilai pekerjaan",rp(jobs.reduce((s,j)=>s+j.price,0))],["Piutang",rp(jobs.reduce((s,j)=>s+j.price-j.paid,0))]]}/><Report title="Keuangan" data={[["Pendapatan",rp(income)],["Pengeluaran",rp(expense)],["Bonus teknisi",rp(bonus)],["Laba",rp(income-expense-bonus)]]}/><Report title="Persediaan" data={[["Jenis bahan",stocks.length],["Stok kritis",low.length],["Nilai stok",rp(stocks.reduce((s,x)=>s+x.qty*x.cost,0))],["Status opname","Aktif"]]}/></div></>}
 </div></section>{modal&&<div className="modal-backdrop" onMouseDown={()=>{setModal("");setEdit(null)}}><section className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal("")}>×</button>{modal==="job"&&<JobForm works={works} submit={submitJob}/>} {modal==="work"&&<WorkForm edit={edit} submit={submitWork}/>} {modal==="move"&&<MoveForm stocks={stocks} submit={submitMove}/>} {modal==="cash"&&<CashForm submit={submitCash}/>}</section></div>}</main>}

function Head({title,sub}:{title:string;sub:string}){return <div className="panel-head"><div><h2>{title}</h2><p>{sub}</p></div></div>};
function Toolbar({title,sub,button,click}:{title:string;sub:string;button?:string;click?:()=>void}){return <div className="toolbar"><div><b>{title}</b><span>{sub}</span></div>{button&&<button className="primary" onClick={click}>{button}</button>}</div>}
function Metrics({jobs,low,income,expense,bonus,finance}:{jobs:Job[];low:number;income:number;expense:number;bonus:number;finance?:boolean}){const data=finance?[["↓",rp(income),"Total pemasukan"],["↑",rp(expense),"Total pengeluaran"],["=",rp(income-expense-bonus),"Laba setelah bonus"]]:[["◈",jobs.filter(j=>j.status!=="Selesai").length,"Pekerjaan aktif"],["✓",jobs.filter(j=>j.status==="Selesai").length,"Selesai bulan ini"],["▣",low,"Stok kritis"],["Rp",rp(income-expense-bonus),"Laba operasional"]];return <div className={`metrics ${finance?"three":""}`}>{data.map((x,i)=><article key={String(x[2])}><span className={["mint","blue","orange","violet"][i]}>{x[0]}</span><strong>{x[1]}</strong><p>{x[2]}</p><small>Data bulan Juli 2026</small></article>)}</div>}
function JobTable({jobs,works,action}:{jobs:Job[];works:Work[];action?:(j:Job)=>React.ReactNode}){return <div className="table-wrap"><table><thead><tr><th>ORDER & PASIEN</th><th>PEKERJAAN</th><th>TEKNISI</th><th>TENGGAT</th><th>STATUS</th><th>TAGIHAN</th>{action&&<th>AKSI</th>}</tr></thead><tbody>{jobs.map(j=><tr key={j.id}><td><b>{j.id}</b><span>{j.patient} · {j.clinic}</span></td><td><b>{works.find(w=>w.id===j.work)?.name}</b><span>Gigi {j.teeth}</span></td><td>{j.tech}</td><td><b>{j.due}</b></td><td><span className={`status s-${j.status.toLowerCase()}`}>{j.status}</span></td><td><b>{rp(j.price-j.paid)}</b><span>{j.paid===j.price?"Lunas":"Belum lunas"}</span></td>{action&&<td>{action(j)}</td>}</tr>)}</tbody></table></div>}
function SimpleTable({heads,rows}:{heads:string[];rows:string[][]}){return <table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table>}
function Report({title,data}:{title:string;data:(string|number)[][]}){return <article className="panel report-card"><h3>{title}</h3>{data.map((x,i)=><p key={i}><span>{x[0]}</span><b>{x[1]}</b></p>)}</article>}
const F=({label,children}:{label:string;children:React.ReactNode})=><label>{label}{children}</label>;
function JobForm({works,submit}:{works:Work[];submit:(e:FormEvent<HTMLFormElement>)=>void}){return <><p className="eyebrow">ORDER BARU</p><h2>Catat pekerjaan masuk</h2><form onSubmit={submit}><div className="form-grid"><F label="Nama pasien"><input name="patient" required/></F><F label="Klinik / dokter"><input name="clinic" required/></F><F label="Jenis pekerjaan"><select name="work">{works.map(w=><option value={w.id} key={w.id}>{w.name}</option>)}</select></F><F label="Nomor gigi / rahang"><input name="teeth"/></F><F label="Teknisi"><select name="tech"><option>Andi</option><option>Dimas</option><option>Rizal</option><option>Lina</option></select></F><F label="Target selesai"><input type="date" name="due" required/></F><F label="Harga kesepakatan"><input type="number" name="price" placeholder="Kosongkan untuk tarif standar"/></F></div><button className="primary save">Simpan pekerjaan</button></form></>}
function WorkForm({edit,submit}:{edit:Work|null;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <><p className="eyebrow">MASTER TARIF</p><h2>{edit?"Edit jenis pekerjaan":"Jenis pekerjaan baru"}</h2><form onSubmit={submit}><div className="form-grid"><F label="Nama tindakan"><input name="name" required defaultValue={edit?.name}/></F><F label="Kategori"><input name="category" required defaultValue={edit?.category}/></F><F label="Tarif jual"><input type="number" name="price" required defaultValue={edit?.price}/></F><F label="Bonus teknisi"><input type="number" name="bonus" required defaultValue={edit?.bonus}/></F><F label="Estimasi hari"><input type="number" name="days" required defaultValue={edit?.days}/></F></div><button className="primary save">Simpan tarif</button></form></>}
function MoveForm({stocks,submit}:{stocks:Stock[];submit:(e:FormEvent<HTMLFormElement>)=>void}){return <><p className="eyebrow">PERSEDIAAN</p><h2>Mutasi & stok opname</h2><form onSubmit={submit}><div className="form-grid"><F label="Bahan"><select name="stock">{stocks.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></F><F label="Jenis"><select name="type"><option>Masuk</option><option>Keluar</option><option>Stok Opname</option></select></F><F label="Jumlah"><input type="number" step=".01" name="qty" required/></F><F label="Tanggal"><input type="date" name="date" defaultValue="2026-07-15"/></F><F label="Keterangan"><input name="note"/></F></div><button className="primary save">Simpan pergerakan</button></form></>}
function CashForm({submit}:{submit:(e:FormEvent<HTMLFormElement>)=>void}){return <><p className="eyebrow">BUKU KAS</p><h2>Transaksi baru</h2><form onSubmit={submit}><div className="form-grid"><F label="Jenis"><select name="type"><option>Masuk</option><option>Keluar</option></select></F><F label="Kategori"><input name="category" required/></F><F label="Nominal"><input type="number" name="amount" required/></F><F label="Tanggal"><input type="date" name="date" defaultValue="2026-07-15"/></F><F label="Keterangan"><input name="note"/></F></div><button className="primary save">Simpan transaksi</button></form></>}
