"use client";
import {FormEvent,useEffect,useState} from "react";
import Image from "next/image";

type Job={id:string;patient:string;clinic:string;partnerId?:number;work:number;workName?:string;workCategory?:string;teeth:string;tech:string;assistant?:string;courier?:string;feeTech?:number;feeAssistant?:number;feeCourier?:number;status:string;due:string;price:number;paid:number};
type Stock={id:number;sku:string;name:string;unit:string;qty:number;min:number;cost:number};
type Move={id:number;stock:number;type:string;qty:number;date:string;note:string};
type Cash={id:number;type:"Masuk"|"Keluar";category:string;amount:number;date:string;note:string};
type Role="Owner"|"Admin"|"Teknisi"|"Asisten Teknisi"|"Kurir";
type User={id:number;name:string;username:string;passwordHash:string;salt:string;role:Role;active:boolean};
type ExtraBonus={id:number;tech:string;amount:number;note:string;date:string};
type Partner={id:number;doctor:string;clinic:string;phone:string;email:string;rewardPoints:number;lastReward:string;promo:string;promoAt:string;active:boolean};
type Brand={name:string;subtitle:string;logo:string};
const workerRoles:Role[]=["Teknisi","Asisten Teknisi","Kurir"];
const handlesJob=(u:User,j:Job)=>u.role==="Teknisi"?j.tech===u.name:u.role==="Asisten Teknisi"?j.assistant===u.name:u.role==="Kurir"?j.courier===u.name:false;
const jobFee=(u:User,j:Job)=>u.role==="Teknisi"?(j.feeTech||0):u.role==="Asisten Teknisi"?(j.feeAssistant||0):u.role==="Kurir"?(j.feeCourier||0):0;
const nextId=(items:{id:number}[])=>items.reduce((max,item)=>Math.max(max,item.id),0)+1;
const normalizeUsername=(value:string)=>value.trim().toLowerCase();
const makeSalt=()=>Array.from(crypto.getRandomValues(new Uint8Array(16)),x=>x.toString(16).padStart(2,"0")).join("");
async function hashPassword(password:string,salt:string){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]),saltBytes=Uint8Array.from(salt.match(/.{2}/g)||[],x=>parseInt(x,16)),bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:saltBytes,iterations:120000,hash:"SHA-256"},key,256);return Array.from(new Uint8Array(bits),x=>x.toString(16).padStart(2,"0")).join("")}
const fileToDataUrl=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file)});
const jobs0:Job[]=[];
const stock0:Stock[]=[];
const cash0:Cash[]=[];
const users0:User[]=[];
const partners0:Partner[]=[];
const brand0:Brand={name:"DentaLab Pro",subtitle:"Laboratory ERP",logo:""};
const menus=["Dashboard","Pekerjaan","Dokter & Klinik","Stok Bahan","Barang Masuk/Keluar","Keuangan","Fee Tim","Akun & Akses","Pengaturan Lab","Laporan"],icons=["⌂","◈","♡","▣","⇅","◒","★","♙","⚙","▤"],rp=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
function useStored<T>(key:string,start:T){const[v,setV]=useState(start),[ready,setReady]=useState(false);useEffect(()=>{const id=window.setTimeout(()=>{const x=localStorage.getItem(key);if(x)setV(JSON.parse(x));setReady(true)},0);return()=>window.clearTimeout(id)},[key]);useEffect(()=>{if(ready)localStorage.setItem(key,JSON.stringify(v))},[key,ready,v]);return[v,setV,ready]as const}

export default function Home(){
 const[active,setActive]=useState("Dashboard"),[search,setSearch]=useState(""),[modal,setModal]=useState(""),[sessionId,setSessionId]=useState<number|null>(null),[sessionReady,setSessionReady]=useState(false),[authError,setAuthError]=useState(""),[selectedJob,setSelectedJob]=useState<Job|null>(null),[selectedPartner,setSelectedPartner]=useState<Partner|null>(null),[selectedStock,setSelectedStock]=useState<Stock|null>(null);
 const[jobs,setJobs]=useStored("dl-v5-jobs",jobs0),[stocks,setStocks]=useStored("dl-v5-stock",stock0),[moves,setMoves]=useStored<Move[]>("dl-v5-moves",[]),[cash,setCash]=useStored("dl-v5-cash",cash0),[users,setUsers,usersReady]=useStored("dl-v6-users",users0),[extras,setExtras]=useStored<ExtraBonus[]>("dl-v5-extra-bonus",[]),[partners,setPartners]=useStored("dl-v6-partners",partners0),[brand,setBrand]=useStored("dl-v6-brand",brand0);
 useEffect(()=>{const id=window.setTimeout(()=>{const saved=sessionStorage.getItem("dl-v6-session");setSessionId(saved?Number(saved):null);setSessionReady(true)},0);return()=>window.clearTimeout(id)},[]);
 const handleOwnerSetup=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),password=String(f.get("password")),salt=makeSalt(),owner:User={id:1,name:String(f.get("name")),username:normalizeUsername(String(f.get("username"))),passwordHash:await hashPassword(password,salt),salt,role:"Owner",active:true};setUsers([owner]);setBrand({...brand,name:String(f.get("labName"))||brand.name});sessionStorage.setItem("dl-v6-session","1");setSessionId(1);setAuthError("")};
 const handleLogin=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),username=normalizeUsername(String(f.get("username"))),password=String(f.get("password")),user=users.find(u=>u.username===username&&u.active);if(!user||await hashPassword(password,user.salt)!==user.passwordHash){setAuthError("Username atau password tidak sesuai.");return}sessionStorage.setItem("dl-v6-session",String(user.id));setSessionId(user.id);setActive("Dashboard");setAuthError("")};
 const logout=()=>{sessionStorage.removeItem("dl-v6-session");setSessionId(null);setAuthError("")};
 const submitUser=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),username=normalizeUsername(String(f.get("username"))),password=String(f.get("password"));if(users.some(u=>u.username===username)){alert("Username sudah digunakan.");return}const salt=makeSalt(),role=String(f.get("role"))as Role;setUsers([...users,{id:nextId(users),name:String(f.get("name")),username,passwordHash:await hashPassword(password,salt),salt,role,active:true}]);setModal("")};
 const resetPassword=async(user:User)=>{const password=prompt(`Password baru untuk ${user.username} (minimal 8 karakter)`);if(password===null)return;if(password.length<8){alert("Password minimal 8 karakter.");return}const salt=makeSalt(),passwordHash=await hashPassword(password,salt);setUsers(users.map(u=>u.id===user.id?{...u,salt,passwordHash}:u));alert("Password berhasil diperbarui.")};
 const submitPartner=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),record:Partner={id:selectedPartner?.id||nextId(partners),doctor:String(f.get("doctor")),clinic:String(f.get("clinic")),phone:String(f.get("phone")),email:String(f.get("email")),rewardPoints:selectedPartner?.rewardPoints||0,lastReward:selectedPartner?.lastReward||"",promo:selectedPartner?.promo||"",promoAt:selectedPartner?.promoAt||"",active:true};setPartners(selectedPartner?partners.map(p=>p.id===record.id?record:p):[record,...partners]);setSelectedPartner(null);setModal("")};
 const addReward=(partner:Partner)=>{const points=prompt(`Tambahkan poin reward untuk ${partner.doctor}`,"1");if(points===null)return;const note=prompt("Keterangan reward","Reward loyalitas");if(note===null)return;setPartners(partners.map(p=>p.id===partner.id?{...p,rewardPoints:p.rewardPoints+(Number(points)||0),lastReward:`${note} · 16 Jul 2026`}:p))};
 const togglePromo=(partner:Partner)=>{if(partner.promo){if(confirm(`Hapus penanda promo ${partner.doctor}?`))setPartners(partners.map(p=>p.id===partner.id?{...p,promo:"",promoAt:""}:p));return}const promo=prompt("Nama promo yang diberikan","Promo loyalitas");if(promo)setPartners(partners.map(p=>p.id===partner.id?{...p,promo,promoAt:"16 Jul 2026"}:p))};
 const submitBrand=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),file=f.get("logo")as File;let logo=brand.logo;if(file?.size){if(file.size>1000000){alert("Ukuran logo maksimal 1 MB.");return}logo=await fileToDataUrl(file)}setBrand({name:String(f.get("name")),subtitle:String(f.get("subtitle")),logo})};
 if(!usersReady||!sessionReady)return <AuthLoading brand={brand}/>;
 if(users.length===0)return <OwnerSetup brand={brand} submit={handleOwnerSetup}/>;
 const me=users.find(u=>u.id===sessionId&&u.active);
 if(!me)return <LoginScreen brand={brand} error={authError} submit={handleLogin}/>;
 const manage=me.role==="Owner"||me.role==="Admin",visibleMenus=manage?menus:["Dashboard","Pekerjaan","Fee Tim"],income=cash.filter(x=>x.type==="Masuk").reduce((s,x)=>s+x.amount,0),expense=cash.filter(x=>x.type==="Keluar").reduce((s,x)=>s+x.amount,0),done=jobs.filter(j=>j.status==="Selesai"),autoBonus=done.reduce((s,j)=>s+(j.feeTech||0)+(j.feeAssistant||0)+(j.feeCourier||0),0),bonus=autoBonus+extras.reduce((s,x)=>s+x.amount,0),low=stocks.filter(x=>x.qty<=x.min);
 const assigned=(j:Job)=>manage||(me.role==="Teknisi"&&j.tech===me.name)||(me.role==="Asisten Teknisi"&&j.assistant===me.name)||(me.role==="Kurir"&&j.courier===me.name);
 const list=jobs.filter(j=>assigned(j)&&`${j.id} ${j.patient} ${j.clinic} ${j.workName||""}`.toLowerCase().includes(search.toLowerCase()));
 const submitJob=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),partnerId=Number(f.get("partnerId"))||undefined,partner=partners.find(p=>p.id===partnerId),clinic=partner?`${partner.doctor} · ${partner.clinic}`:String(f.get("clinic"))||"Pengirim umum";setJobs([{id:`DL-${new Date().toISOString().slice(2,10).replaceAll("-","")}-${String(jobs.length+1).padStart(3,"0")}`,patient:String(f.get("patient")),clinic,partnerId,work:0,workName:String(f.get("workName")),workCategory:String(f.get("workCategory")),teeth:String(f.get("teeth")),tech:String(f.get("tech")),assistant:String(f.get("assistant")),courier:String(f.get("courier")),feeTech:Number(f.get("feeTech"))||0,feeAssistant:Number(f.get("feeAssistant"))||0,feeCourier:Number(f.get("feeCourier"))||0,status:"Model",due:String(f.get("due")),price:Number(f.get("price"))||0,paid:0},...jobs]);setModal("");setActive("Pekerjaan")};
 const advanceJob=(j:Job)=>{const stages=["Model","Produksi","Finishing","QC","Selesai"],next=stages[Math.min(stages.indexOf(j.status)+1,stages.length-1)];if(j.status==="Selesai")return;if(next==="Selesai"){setSelectedJob(j);setModal("complete");return}if(confirm(`Lanjutkan ${j.id} dari ${j.status} ke ${next}?`))setJobs(jobs.map(x=>x.id===j.id?{...x,status:next}:x))};
 const editJobFees=(j:Job)=>{const feeTech=prompt(`Fee Teknisi ${j.tech}`,String(j.feeTech||0));if(feeTech===null)return;const feeAssistant=prompt(`Fee Asisten ${j.assistant||"(tidak ada)"}`,String(j.feeAssistant||0));if(feeAssistant===null)return;const feeCourier=prompt(`Fee Kurir ${j.courier||"(tidak ada)"}`,String(j.feeCourier||0));if(feeCourier===null)return;setJobs(jobs.map(x=>x.id===j.id?{...x,feeTech:Number(feeTech)||0,feeAssistant:Number(feeAssistant)||0,feeCourier:Number(feeCourier)||0}:x))};
 const submitMove=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),id=Number(f.get("stock")),type=String(f.get("type")),q=Number(f.get("qty"));setStocks(stocks.map(x=>x.id===id?{...x,qty:type==="Masuk"?x.qty+q:type==="Keluar"?Math.max(0,x.qty-q):q}:x));setMoves([{id:nextId(moves),stock:id,type,qty:q,date:String(f.get("date")),note:String(f.get("note"))},...moves]);setModal("")};
 const submitStock=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),record:Stock={id:selectedStock?.id||nextId(stocks),sku:String(f.get("sku")).trim(),name:String(f.get("name")).trim(),unit:String(f.get("unit")).trim(),qty:Number(f.get("qty")),min:Number(f.get("min")),cost:Number(f.get("cost"))};setStocks(selectedStock?stocks.map(x=>x.id===record.id?record:x):[...stocks,record]);if(selectedStock&&selectedStock.qty!==record.qty)setMoves([{id:nextId(moves),stock:record.id,type:"Stok Opname",qty:record.qty,date:"2026-07-16",note:"Perubahan melalui Edit Bahan"},...moves]);setSelectedStock(null);setModal("")};
 const submitCash=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setCash([{id:nextId(cash),type:String(f.get("type"))as Cash["type"],category:String(f.get("category")),amount:Number(f.get("amount")),date:String(f.get("date")),note:String(f.get("note"))},...cash]);setModal("")};
 return <main className="app-shell"><aside className="sidebar"><div className="brand">{brand.logo?<Image className="brand-mark brand-image" src={brand.logo} alt={`Logo ${brand.name}`} width={40} height={40} unoptimized/>:<span className="brand-mark">{brand.name.slice(0,2).toUpperCase()}</span>}<div><b>{brand.name}</b><small>{brand.subtitle}</small></div></div><nav>{visibleMenus.map(m=>{const i=menus.indexOf(m);return <button key={m} className={active===m?"active":""} onClick={()=>setActive(m)}><span className="nav-icon">{icons[i]}</span>{m}{m==="Stok Bahan"&&low.length>0&&<em>{low.length}</em>}</button>})}</nav><div className="side-card"><span>●</span><div><b>Akses {me.role} aktif</b><small>{manage?"Kontrol penuh operasional":"Pekerjaan & fee pribadi"}</small></div></div><button className="profile" onClick={logout} title="Keluar dari aplikasi"><span>{me.name.slice(0,2).toUpperCase()}</span><div><b>{me.name}</b><small>@{me.username} · Keluar</small></div></button></aside><section className="workspace"><header className="topbar"><label className="search">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari order, pasien, dokter, atau klinik..."/></label><div className="account-current"><span>{me.name.slice(0,2).toUpperCase()}</span><div><b>{me.name}</b><small>{me.role}</small></div></div>{manage&&users.some(u=>u.role==="Teknisi"&&u.active)&&<button className="primary" onClick={()=>setModal("job")}>＋ Pekerjaan Baru</button>}<button className="logout-btn" onClick={logout}>Keluar</button></header><div className="content"><div className="heading"><div><p className="eyebrow">{me.role.toUpperCase()} WORKSPACE · 16 JULI 2026</p><h1>{active}</h1><p>{manage?"Kelola pekerjaan, tim, mitra klinik, fee, keuangan, dan bahan dalam satu alur.":`Selamat datang ${me.name}. Perbarui progres pekerjaan Anda hari ini.`}</p></div><span className="system-live">● Login {me.role} aktif</span></div>
 {active==="Dashboard"&&<><section className="dashboard-hero"><div><span>OPERASIONAL LAB TERPADU</span><h2>Selamat datang, {me.name}</h2><p>{manage?"Bangun alur kerja lab Anda dari awal dengan data yang bersih dan terstruktur.":"Fokus pada pekerjaan hari ini dan catat setiap progres dengan cepat."}</p></div><div className="hero-score"><strong>{jobs.filter(j=>j.status!=="Selesai").length}</strong><span>Pekerjaan aktif</span></div></section>{manage&&jobs.length===0&&<SetupGuide users={users} stocks={stocks} go={setActive} openJob={()=>setModal("job")}/>}<Metrics jobs={jobs} low={low.length} income={income} expense={expense} bonus={bonus}/><div className="main-grid"><section className="panel jobs-panel"><Head title="Pekerjaan berjalan" sub="Prioritas berdasarkan tenggat"/><JobTable jobs={list.slice(0,6)}/></section><aside className="right-stack"><section className="panel"><Head title="Stok kritis" sub="Perlu segera ditindaklanjuti"/>{low.length===0?<div className="mini-empty">Belum ada stok kritis</div>:low.map(x=><div className="stock-row" key={x.id}><span className="stock-icon red">▣</span><div><b>{x.name}</b><small>Minimum {x.min} {x.unit}</small></div><strong>{x.qty} {x.unit}</strong></div>)}</section><section className="panel cash-mini"><Head title="Keuangan bulan ini" sub="Ringkasan kas berjalan"/><p><span>Pendapatan</span><b>{rp(income)}</b></p><p><span>Pengeluaran</span><b>{rp(expense)}</b></p><p><span>Fee tim</span><b>{rp(bonus)}</b></p><p className="profit"><span>Laba operasional</span><b>{rp(income-expense-bonus)}</b></p></section></aside></div></>}
 {active==="Pekerjaan"&&<><section className="workflow-strip strong-flow"><div className="stage-model"><span>1</span><b>MODEL</b></div><i>→</i><div className="stage-production"><span>2</span><b>PRODUKSI</b></div><i>→</i><div className="stage-finishing"><span>3</span><b>FINISHING</b></div><i>→</i><div className="stage-qc"><span>4</span><b>QUALITY CONTROL</b></div><i>→</i><div className="finish"><span>✓</span><b>SELESAI & FEE</b></div></section><section className="panel page"><Toolbar title={`${list.length} pekerjaan`} sub={manage?"Kelola jenis pekerjaan, tim, fee, progres, dan pembayaran":"Daftar pekerjaan yang ditugaskan kepada Anda"} button={manage&&users.some(u=>u.role==="Teknisi")?"＋ Pekerjaan Baru":undefined} click={()=>setModal("job")}/><JobTable jobs={list} hideMoney={!manage} action={j=><div className="row-actions">{j.status!=="Selesai"&&<button className="progress-btn" onClick={()=>advanceJob(j)}>Lanjutkan →</button>}{j.status==="Selesai"&&<span className="completed-mark">✓ Terkonfirmasi</span>}{manage&&<><button onClick={()=>editJobFees(j)}>Fee</button><button onClick={()=>{const n=prompt("Harga pekerjaan",String(j.price));if(n)setJobs(jobs.map(x=>x.id===j.id?{...x,price:Number(n)}:x))}}>Harga</button><button onClick={()=>{const n=prompt("Jumlah pembayaran",String(j.price-j.paid));if(n){setJobs(jobs.map(x=>x.id===j.id?{...x,paid:Math.min(x.price,x.paid+Number(n))}:x));setCash([{id:nextId(cash),type:"Masuk",category:"Pembayaran pekerjaan",amount:Number(n),date:"2026-07-16",note:j.id},...cash])}}}>Bayar</button><button className="danger" onClick={()=>confirm(`Hapus ${j.id}?`)&&setJobs(jobs.filter(x=>x.id!==j.id))}>Hapus</button></>}</div>}/></section></>}
 {active==="Dokter & Klinik"&&manage&&<section className="panel page partner-page"><Toolbar title="Database dokter & klinik pengirim" sub="Kontak, histori order, reward, dan penanda promo laboratorium" button="＋ Tambah Pengirim" click={()=>{setSelectedPartner(null);setModal("partner")}}/>{partners.length===0?<Empty title="Belum ada dokter atau klinik" text="Tambahkan pengirim pertama agar dapat dipilih saat mencatat pekerjaan."/>:<div className="table-wrap"><table><thead><tr><th>DOKTER</th><th>KLINIK</th><th>KONTAK</th><th>HISTORI ORDER</th><th>REWARD</th><th>PROMO</th><th>AKSI</th></tr></thead><tbody>{partners.map(p=>{const orders=jobs.filter(j=>j.partnerId===p.id),value=orders.reduce((sum,j)=>sum+j.price,0);return <tr key={p.id}><td><b>{p.doctor}</b><span>{p.email||"Email belum diisi"}</span></td><td><b>{p.clinic}</b></td><td><a className="wa-link" href={`https://wa.me/${p.phone.replace(/\D/g,"").replace(/^0/,"62")}`} target="_blank" rel="noreferrer">{p.phone}</a></td><td><b>{orders.length} pekerjaan</b><span>{rp(value)}</span></td><td><b>{p.rewardPoints} poin</b><span>{p.lastReward||"Belum ada reward"}</span></td><td>{p.promo?<span className="promo-badge">✓ {p.promo}<small>{p.promoAt}</small></span>:<span className="no-promo">Belum menerima promo</span>}</td><td><div className="row-actions partner-actions"><button onClick={()=>addReward(p)}>＋ Reward</button><button onClick={()=>togglePromo(p)}>{p.promo?"Reset Promo":"Tandai Promo"}</button><button onClick={()=>{setSelectedPartner(p);setModal("partner")}}>Edit</button><button className="danger" onClick={()=>confirm(`Hapus data ${p.doctor}?`)&&setPartners(partners.filter(x=>x.id!==p.id))}>Hapus</button></div></td></tr>})}</tbody></table></div>}</section>}
 {active==="Stok Bahan"&&<><div className="toolbar"><div><b>Persediaan bahan habis pakai</b><span>Nilai stok {rp(stocks.reduce((s,x)=>s+x.qty*x.cost,0))}</span></div><div className="toolbar-actions"><button className="secondary" onClick={()=>{setSelectedStock(null);setModal("stocknew")}}>＋ Tambah Bahan</button>{stocks.length>0&&<button className="primary" onClick={()=>setModal("move")}>Mutasi / Opname</button>}</div></div>{stocks.length===0?<Empty title="Belum ada bahan" text="Tambahkan bahan habis pakai pertama untuk memulai persediaan."/>:<div className="stock-grid">{stocks.map(s=><article className={`material ${s.qty<=s.min?"critical":""}`} key={s.id}><div><small>{s.sku}</small><em>{s.qty<=s.min?"KRITIS":"AMAN"}</em></div><h3>{s.name}</h3><strong>{s.qty} <small>{s.unit}</small></strong><p>Minimum {s.min} · {rp(s.cost)}/{s.unit}</p><div className="material-actions"><button onClick={()=>{const n=prompt("Jumlah stok fisik",String(s.qty));if(n!==null)setStocks(stocks.map(x=>x.id===s.id?{...x,qty:Number(n)}:x))}}>Koreksi stok opname</button><button className="edit-material" onClick={()=>{setSelectedStock(s);setModal("stockedit")}}>Edit bahan</button></div></article>)}</div>}</>}
 {active==="Barang Masuk/Keluar"&&<section className="panel page"><Toolbar title="Kartu stok" sub="Barang masuk, pemakaian, dan koreksi opname" button="＋ Catat Pergerakan" click={()=>setModal("move")}/><SimpleTable heads={["TANGGAL","BAHAN","JENIS","JUMLAH","KETERANGAN"]} rows={moves.map(m=>[m.date,stocks.find(s=>s.id===m.stock)?.name||"-",m.type,String(m.qty),m.note])}/></section>}
 {active==="Keuangan"&&<><Metrics jobs={jobs} low={low.length} income={income} expense={expense} bonus={bonus} finance/><section className="panel page"><Toolbar title="Buku kas laboratorium" sub="Pemasukan dan pengeluaran tercatat" button="＋ Transaksi" click={()=>setModal("cash")}/><table><thead><tr><th>TANGGAL</th><th>TIPE</th><th>KATEGORI</th><th>KETERANGAN</th><th>NOMINAL</th><th>AKSI</th></tr></thead><tbody>{cash.map(c=><tr key={c.id}><td>{c.date}</td><td>{c.type}</td><td>{c.category}</td><td>{c.note}</td><td><b>{rp(c.amount)}</b></td><td><button className="text-danger" onClick={()=>confirm("Hapus transaksi ini?")&&setCash(cash.filter(x=>x.id!==c.id))}>Hapus</button></td></tr>)}</tbody></table></section></>}
 {active==="Fee Tim"&&<><div className="toolbar"><div><b>Fee tim · Juli 2026</b><span>Fee Teknisi, Asisten Teknisi, dan Kurir tercatat otomatis saat pekerjaan selesai</span></div>{manage&&users.some(u=>workerRoles.includes(u.role)&&u.active)&&<button className="primary" onClick={()=>setModal("bonus")}>＋ Fee Tambahan</button>}</div>{users.some(u=>workerRoles.includes(u.role))?<div className="bonus-grid">{users.filter(u=>workerRoles.includes(u.role)&&(manage||u.id===me.id)).map(u=>{const completed=done.filter(j=>handlesJob(u,j)),automatic=completed.reduce((s,j)=>s+jobFee(u,j),0),extra=extras.filter(x=>x.tech===u.name).reduce((s,x)=>s+x.amount,0);return <article className="panel tech bonus-detail" key={u.id}><span>{u.name.slice(0,2).toUpperCase()}</span><div><small>{u.role.toUpperCase()}</small><h3>{u.name}</h3><p>{completed.length} pekerjaan selesai · Fee otomatis {rp(automatic)}</p><p>Tambahan owner/admin · {rp(extra)}</p></div><strong>{rp(automatic+extra)}</strong></article>})}</div>:<Empty title="Belum ada anggota produksi" text="Buat akun Teknisi, Asisten Teknisi, atau Kurir melalui menu Akun & Akses."/>}{manage&&extras.length>0&&<section className="panel extra-list"><Head title="Riwayat fee tambahan" sub="Penyesuaian fee oleh Owner atau Admin"/>{extras.map(x=><p key={x.id}><span><b>{x.tech}</b><small>{x.date} · {x.note}</small></span><strong>{rp(x.amount)}</strong><button onClick={()=>setExtras(extras.filter(e=>e.id!==x.id))}>Hapus</button></p>)}</section>}</>}
 {active==="Akun & Akses"&&manage&&<section className="panel page"><Toolbar title="Akun pengguna" sub="Setiap pengguna memiliki username, password, peran, dan ruang kerja sendiri" button="＋ Tambah Akun" click={()=>setModal("user")}/><table><thead><tr><th>NAMA & USERNAME</th><th>PERAN</th><th>AKSES</th><th>STATUS</th><th>AKSI</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.name}</b><span>@{u.username}</span></td><td><span className={`role role-${u.role.toLowerCase().replaceAll(" ","-")}`}>{u.role}</span></td><td>{workerRoles.includes(u.role)?"Pekerjaan & fee sendiri":"Seluruh modul operasional"}</td><td>{u.active?"Aktif":"Nonaktif"}</td><td><div className="row-actions">{(u.role!=="Owner"||me.role==="Owner")&&<button onClick={()=>resetPassword(u)}>Reset Password</button>}{u.role!=="Owner"&&<><button onClick={()=>setUsers(users.map(x=>x.id===u.id?{...x,active:!x.active}:x))}>{u.active?"Nonaktifkan":"Aktifkan"}</button><button className="danger" onClick={()=>confirm(`Hapus akun ${u.name}?`)&&setUsers(users.filter(x=>x.id!==u.id))}>Hapus</button></>}</div></td></tr>)}</tbody></table></section>}
 {active==="Pengaturan Lab"&&manage&&<BrandSettings brand={brand} submit={submitBrand} removeLogo={()=>setBrand({...brand,logo:""})}/>}
 {active==="Laporan"&&<><section className="report"><div><p className="eyebrow">LAPORAN MANAJEMEN · JULI 2026</p><h2>Kinerja Laboratorium</h2><p>Ringkasan operasional siap cetak.</p></div><button onClick={()=>window.print()}>Cetak / Simpan PDF</button></section><div className="report-grid"><Report title="Operasional" data={[["Total order",jobs.length],["Order selesai",done.length],["Nilai pekerjaan",rp(jobs.reduce((s,j)=>s+j.price,0))],["Piutang",rp(jobs.reduce((s,j)=>s+j.price-j.paid,0))]]}/><Report title="Keuangan" data={[["Pendapatan",rp(income)],["Pengeluaran",rp(expense)],["Fee tim",rp(bonus)],["Laba",rp(income-expense-bonus)]]}/><Report title="Persediaan" data={[["Jenis bahan",stocks.length],["Stok kritis",low.length],["Nilai stok",rp(stocks.reduce((s,x)=>s+x.qty*x.cost,0))],["Status opname","Aktif"]]}/></div></>}
 </div></section>{modal&&<div className="modal-backdrop" onMouseDown={()=>{setModal("");setSelectedJob(null);setSelectedPartner(null);setSelectedStock(null)}}><section className="modal job-modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>{setModal("");setSelectedPartner(null);setSelectedStock(null)}}>×</button>{modal==="job"&&<JobForm users={users} partners={partners} submit={submitJob}/>} {modal==="complete"&&selectedJob&&<CompleteForm job={selectedJob} confirm={()=>{setJobs(jobs.map(x=>x.id===selectedJob.id?{...x,status:"Selesai"}:x));setSelectedJob(null);setModal("")}}/>} {modal==="partner"&&<PartnerForm edit={selectedPartner} submit={submitPartner}/>} {modal==="move"&&<MoveForm stocks={stocks} submit={submitMove}/>} {(modal==="stocknew"||modal==="stockedit")&&<StockNewForm stock={modal==="stockedit"?selectedStock:null} submit={submitStock}/>} {modal==="cash"&&<CashForm submit={submitCash}/>} {modal==="bonus"&&<BonusForm users={users} submit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setExtras([{id:nextId(extras),tech:String(f.get("tech")),amount:Number(f.get("amount")),note:String(f.get("note")),date:"2026-07-16"},...extras]);setModal("")}}/>} {modal==="user"&&<UserForm submit={submitUser}/>}</section></div>}</main>}

function BrandIdentity({brand}:{brand:Brand}){return <div className="auth-brand">{brand.logo?<Image src={brand.logo} alt={`Logo ${brand.name}`} width={46} height={46} unoptimized/>:<span>{brand.name.slice(0,2).toUpperCase()}</span>}<div><b>{brand.name}</b><small>{brand.subtitle}</small></div></div>}
function AuthLoading({brand}:{brand:Brand}){return <main className="auth-shell"><section className="auth-card auth-loading"><BrandIdentity brand={brand}/><div className="auth-loader"/><p>Menyiapkan ruang kerja laboratorium…</p></section></main>}
function LoginScreen({brand,error,submit}:{brand:Brand;error:string;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <main className="auth-shell"><aside className="auth-story"><span>SISTEM LABORATORIUM TERPADU</span><h1>Setiap anggota tim masuk ke ruang kerjanya sendiri.</h1><p>Admin mengelola operasional. Teknisi, Asisten Teknisi, dan Kurir hanya melihat pekerjaan serta fee yang ditugaskan.</p><div><b>✓</b> Akses berdasarkan peran</div><div><b>✓</b> Progres pekerjaan terpantau</div><div><b>✓</b> Fee tim tercatat otomatis</div></aside><section className="auth-card"><BrandIdentity brand={brand}/><p className="eyebrow">LOGIN PENGGUNA</p><h2>Masuk ke DentaLab</h2><p className="auth-copy">Gunakan username dan password yang diberikan Owner atau Admin.</p><form onSubmit={submit}><F label="Username"><input name="username" autoComplete="username" required autoFocus/></F><F label="Password"><input type="password" name="password" autoComplete="current-password" required/></F>{error&&<div className="auth-error">{error}</div>}<button className="primary save">Masuk ke aplikasi</button></form><small className="auth-help">Hubungi Owner/Admin bila lupa password.</small></section></main>}
function OwnerSetup({brand,submit}:{brand:Brand;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <main className="auth-shell"><aside className="auth-story"><span>AKTIVASI PERTAMA</span><h1>Mulai dengan identitas lab dan akun Owner.</h1><p>Akun pertama memiliki kontrol penuh untuk membuat Admin, Teknisi, Asisten Teknisi, Kurir, dan seluruh data operasional.</p><div><b>1</b> Buat akun Owner</div><div><b>2</b> Tambahkan anggota tim</div><div><b>3</b> Mulai catat pekerjaan</div></aside><section className="auth-card setup-owner"><BrandIdentity brand={brand}/><p className="eyebrow">PENGATURAN AWAL</p><h2>Aktifkan sistem laboratorium</h2><form onSubmit={submit}><F label="Nama laboratorium"><input name="labName" defaultValue={brand.name} required/></F><F label="Nama lengkap Owner"><input name="name" required/></F><F label="Username Owner"><input name="username" minLength={4} autoComplete="username" required/></F><F label="Password Owner"><input type="password" name="password" minLength={8} autoComplete="new-password" required placeholder="Minimal 8 karakter"/></F><button className="primary save">Aktifkan & masuk sebagai Owner</button></form></section></main>}
function BrandSettings({brand,submit,removeLogo}:{brand:Brand;submit:(e:FormEvent<HTMLFormElement>)=>void;removeLogo:()=>void}){return <div className="settings-grid"><section className="panel brand-preview"><p className="eyebrow">PRATINJAU IDENTITAS</p>{brand.logo?<Image src={brand.logo} alt={`Logo ${brand.name}`} width={94} height={94} unoptimized/>:<span>{brand.name.slice(0,2).toUpperCase()}</span>}<h2>{brand.name}</h2><p>{brand.subtitle}</p><small>Identitas ini tampil di halaman login dan menu aplikasi.</small></section><section className="panel brand-form"><Head title="Nama & logo laboratorium" sub="Hanya Owner dan Admin yang dapat mengubah identitas aplikasi"/><form onSubmit={submit}><F label="Nama laboratorium"><input name="name" defaultValue={brand.name} required/></F><F label="Keterangan singkat"><input name="subtitle" defaultValue={brand.subtitle} required/></F><F label="File logo (PNG/JPG, maksimal 1 MB)"><input type="file" name="logo" accept="image/png,image/jpeg,image/webp"/></F><div className="brand-actions"><button className="primary">Simpan identitas lab</button>{brand.logo&&<button type="button" className="secondary" onClick={removeLogo}>Hapus logo</button>}</div></form></section></div>}
function PartnerForm({edit,submit}:{edit:Partner|null;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <><p className="eyebrow">DATABASE PENGIRIM</p><h2>{edit?"Edit dokter & klinik":"Tambah dokter & klinik"}</h2><p className="modal-copy">Data ini dapat dipilih langsung saat mencatat pekerjaan baru.</p><form onSubmit={submit}><div className="form-grid"><F label="Nama dokter"><input name="doctor" required defaultValue={edit?.doctor} placeholder="drg. Nama Dokter"/></F><F label="Nama klinik"><input name="clinic" required defaultValue={edit?.clinic}/></F><F label="Nomor telepon / WhatsApp"><input name="phone" required defaultValue={edit?.phone} placeholder="08xxxxxxxxxx"/></F><F label="Email (opsional)"><input type="email" name="email" defaultValue={edit?.email}/></F></div><button className="primary save">{edit?"Simpan perubahan":"Tambahkan ke database"}</button></form></>}

function Head({title,sub}:{title:string;sub:string}){return <div className="panel-head"><div><h2>{title}</h2><p>{sub}</p></div></div>};
function Toolbar({title,sub,button,click}:{title:string;sub:string;button?:string;click?:()=>void}){return <div className="toolbar"><div><b>{title}</b><span>{sub}</span></div>{button&&<button className="primary" onClick={click}>{button}</button>}</div>}
function Metrics({jobs,low,income,expense,bonus,finance}:{jobs:Job[];low:number;income:number;expense:number;bonus:number;finance?:boolean}){const data=finance?[["↓",rp(income),"Total pemasukan"],["↑",rp(expense),"Total pengeluaran"],["=",rp(income-expense-bonus),"Laba setelah fee tim"]]:[["◈",jobs.filter(j=>j.status!=="Selesai").length,"Pekerjaan aktif"],["✓",jobs.filter(j=>j.status==="Selesai").length,"Selesai bulan ini"],["▣",low,"Stok kritis"],["Rp",rp(income-expense-bonus),"Laba operasional"]];return <div className={`metrics ${finance?"three":""}`}>{data.map((x,i)=><article key={String(x[2])}><span className={["mint","blue","orange","violet"][i]}>{x[0]}</span><strong>{x[1]}</strong><p>{x[2]}</p><small>Data bulan Juli 2026</small></article>)}</div>}
function JobTable({jobs,action,hideMoney}:{jobs:Job[];action?:(j:Job)=>React.ReactNode;hideMoney?:boolean}){return <div className="table-wrap"><table><thead><tr><th>ORDER & PASIEN</th><th>JENIS PEKERJAAN</th><th>TIM PRODUKSI & FEE</th><th>TENGGAT</th><th>PROGRES</th>{!hideMoney&&<th>TAGIHAN</th>}{action&&<th>AKSI</th>}</tr></thead><tbody>{jobs.map(j=><tr key={j.id}><td><b>{j.id}</b><span>{j.patient} · {j.clinic}</span></td><td><b>{j.workName||"Belum diisi"}</b><span>{j.workCategory||"Umum"} · Gigi {j.teeth||"-"}</span></td><td><div className="team-stack"><span><b>T</b>{j.tech} · {rp(j.feeTech||0)}</span>{j.assistant&&<span><b>A</b>{j.assistant} · {rp(j.feeAssistant||0)}</span>}{j.courier&&<span><b>K</b>{j.courier} · {rp(j.feeCourier||0)}</span>}</div></td><td><b>{j.due}</b></td><td><span className={`status s-${j.status.toLowerCase()}`}>{j.status}</span></td>{!hideMoney&&<td><b>{rp(j.price-j.paid)}</b><span>{j.paid===j.price?"Lunas":"Belum lunas"} · Fee tim {rp((j.feeTech||0)+(j.feeAssistant||0)+(j.feeCourier||0))}</span></td>}{action&&<td>{action(j)}</td>}</tr>)}</tbody></table>{jobs.length===0&&<Empty title="Belum ada pekerjaan" text="Buat akun Teknisi lalu catat pekerjaan pertama langsung dari halaman ini."/>}</div>}
function Empty({title,text}:{title:string;text:string}){return <div className="empty-state"><span>◇</span><b>{title}</b><p>{text}</p></div>}
function SetupGuide({users,stocks,go,openJob}:{users:User[];stocks:Stock[];go:(x:string)=>void;openJob:()=>void}){const hasTech=users.some(u=>u.role==="Teknisi"&&u.active),steps=[{done:users.some(u=>workerRoles.includes(u.role)),n:"01",title:"Buat akun tim",text:"Teknisi, Asisten, dan Kurir",run:()=>go("Akun & Akses")},{done:false,n:"02",title:"Catat pekerjaan",text:"Isi jenis, harga, tim, dan fee",run:hasTech?openJob:()=>go("Akun & Akses")},{done:stocks.length>0,n:"03",title:"Masukkan bahan",text:"Catat stok dan batas minimum",run:()=>go("Stok Bahan")}];return <section className="setup-guide"><div className="setup-head"><div><span>PERSIAPAN AWAL</span><h3>Siapkan sistem dalam 3 langkah</h3></div><strong>{steps.filter(s=>s.done).length}/3 selesai</strong></div><div className="setup-steps">{steps.map(s=><button key={s.n} className={s.done?"done":""} onClick={s.run}><i>{s.done?"✓":s.n}</i><span><b>{s.title}</b><small>{s.text}</small></span><em>→</em></button>)}</div></section>}
function SimpleTable({heads,rows}:{heads:string[];rows:string[][]}){return <table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table>}
function Report({title,data}:{title:string;data:(string|number)[][]}){return <article className="panel report-card"><h3>{title}</h3>{data.map((x,i)=><p key={i}><span>{x[0]}</span><b>{x[1]}</b></p>)}</article>}
const F=({label,children}:{label:string;children:React.ReactNode})=><label>{label}{children}</label>;
function JobForm({users,partners,submit}:{users:User[];partners:Partner[];submit:(e:FormEvent<HTMLFormElement>)=>void}){return <><p className="eyebrow">ORDER BARU · DATA, TIM & FEE</p><h2>Catat pekerjaan masuk</h2><div className="form-flow"><b>Model</b><i>→</i><span>Produksi</span><i>→</i><span>Finishing</span><i>→</i><span>QC</span><i>→</i><span>Selesai & fee</span></div><form onSubmit={submit}><div className="form-section"><h3>Informasi pekerjaan & pengirim</h3><div className="form-grid"><F label="Nama pasien"><input name="patient" required/></F><F label="Dokter / klinik dari database"><select name="partnerId"><option value="0">Pilih pengirim terdaftar</option>{partners.filter(p=>p.active).map(p=><option value={p.id} key={p.id}>{p.doctor} · {p.clinic}</option>)}</select></F><F label="Pengirim manual (jika belum terdaftar)"><input name="clinic" placeholder="Nama dokter / klinik"/></F><F label="Jenis pekerjaan"><input name="workName" required placeholder="Contoh: Valplast, Crown Zirconia"/></F><F label="Kategori"><select name="workCategory"><option>Gigi Palsu Lepasan</option><option>Crown & Bridge</option><option>Implan</option><option>Orthodonti</option><option>Repair</option><option>Lainnya</option></select></F><F label="Nomor gigi / rahang"><input name="teeth" placeholder="Contoh: 11-13 / RA"/></F><F label="Target selesai"><input type="date" name="due" required/></F></div></div><div className="form-section fee-section"><h3>Tim produksi & fee per pekerjaan</h3><div className="form-grid"><F label="Teknisi"><select name="tech" required>{users.filter(u=>u.role==="Teknisi"&&u.active).map(u=><option key={u.id}>{u.name}</option>)}</select></F><F label="Fee Teknisi"><input type="number" min="0" name="feeTech" required placeholder="Rp"/></F><F label="Asisten Teknisi (opsional)"><select name="assistant"><option value="">Tanpa asisten</option>{users.filter(u=>u.role==="Asisten Teknisi"&&u.active).map(u=><option key={u.id}>{u.name}</option>)}</select></F><F label="Fee Asisten Teknisi"><input type="number" min="0" name="feeAssistant" placeholder="Rp"/></F><F label="Kurir (opsional)"><select name="courier"><option value="">Tanpa kurir</option>{users.filter(u=>u.role==="Kurir"&&u.active).map(u=><option key={u.id}>{u.name}</option>)}</select></F><F label="Fee Kurir"><input type="number" min="0" name="feeCourier" placeholder="Rp"/></F></div></div><div className="form-section price-section"><F label="Harga pekerjaan ke pelanggan"><input type="number" min="0" name="price" required placeholder="Rp"/></F></div><button className="primary save">Simpan & mulai dari tahap Model</button></form></>}
function CompleteForm({job,confirm}:{job:Job;confirm:()=>void}){const total=(job.feeTech||0)+(job.feeAssistant||0)+(job.feeCourier||0);return <div className="complete-modal"><span className="complete-icon">✓</span><p className="eyebrow">KONFIRMASI AKHIR</p><h2>Selesaikan pekerjaan?</h2><p>Pastikan <b>{job.workName}</b> untuk order <b>{job.id}</b> telah melewati Quality Control dan siap diserahkan.</p><div className="complete-summary fee-confirm"><span><small>Teknisi · {job.tech}</small><b>{rp(job.feeTech||0)}</b></span><span><small>Asisten · {job.assistant||"Tidak ada"}</small><b>{rp(job.feeAssistant||0)}</b></span><span><small>Kurir · {job.courier||"Tidak ada"}</small><b>{rp(job.feeCourier||0)}</b></span><span className="fee-total"><small>Total fee tim</small><b>{rp(total)}</b></span></div><div className="confirm-note">Setelah dikonfirmasi, status menjadi <b>Selesai</b> dan seluruh fee tim otomatis masuk ke laporan bulan berjalan.</div><button className="primary save" onClick={confirm}>✓ Konfirmasi selesai & catat fee tim</button></div>}
function MoveForm({stocks,submit}:{stocks:Stock[];submit:(e:FormEvent<HTMLFormElement>)=>void}){return <><p className="eyebrow">PERSEDIAAN</p><h2>Mutasi & stok opname</h2><form onSubmit={submit}><div className="form-grid"><F label="Bahan"><select name="stock">{stocks.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></F><F label="Jenis"><select name="type"><option>Masuk</option><option>Keluar</option><option>Stok Opname</option></select></F><F label="Jumlah"><input type="number" step=".01" name="qty" required/></F><F label="Tanggal"><input type="date" name="date" defaultValue="2026-07-15"/></F><F label="Keterangan"><input name="note"/></F></div><button className="primary save">Simpan pergerakan</button></form></>}
function CashForm({submit}:{submit:(e:FormEvent<HTMLFormElement>)=>void}){return <><p className="eyebrow">BUKU KAS</p><h2>Transaksi baru</h2><form onSubmit={submit}><div className="form-grid"><F label="Jenis"><select name="type"><option>Masuk</option><option>Keluar</option></select></F><F label="Kategori"><input name="category" required/></F><F label="Nominal"><input type="number" name="amount" required/></F><F label="Tanggal"><input type="date" name="date" defaultValue="2026-07-15"/></F><F label="Keterangan"><input name="note"/></F></div><button className="primary save">Simpan transaksi</button></form></>}
function BonusForm({users,submit}:{users:User[];submit:(e:FormEvent<HTMLFormElement>)=>void}){return <><p className="eyebrow">FEE TAMBAHAN</p><h2>Tambahan untuk anggota tim</h2><form onSubmit={submit}><div className="form-grid"><F label="Pekerja"><select name="tech">{users.filter(u=>workerRoles.includes(u.role)&&u.active).map(u=><option value={u.name} key={u.id}>{u.name} · {u.role}</option>)}</select></F><F label="Nominal tambahan"><input type="number" min="0" name="amount" required/></F><F label="Keterangan"><input name="note" placeholder="Contoh: lembur order urgent" required/></F></div><button className="primary save">Tambahkan fee</button></form></>}
function StockNewForm({stock,submit}:{stock?:Stock|null;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <><p className="eyebrow">MASTER BAHAN</p><h2>{stock?"Edit bahan habis pakai":"Tambah bahan habis pakai"}</h2><p className="modal-copy">{stock?"Ubah identitas bahan, stok, batas minimum, dan harga satuan.":"Masukkan data awal bahan yang akan dipantau."}</p><form onSubmit={submit}><div className="form-grid"><F label="Kode / SKU"><input name="sku" required defaultValue={stock?.sku}/></F><F label="Nama bahan"><input name="name" required defaultValue={stock?.name}/></F><F label="Satuan"><input name="unit" required placeholder="pcs, box, gram, disc" defaultValue={stock?.unit}/></F><F label={stock?"Jumlah stok":"Stok awal"}><input type="number" step=".01" min="0" name="qty" required defaultValue={stock?.qty}/></F><F label="Batas minimum"><input type="number" step=".01" min="0" name="min" required defaultValue={stock?.min}/></F><F label="Harga per satuan"><input type="number" min="0" name="cost" required defaultValue={stock?.cost}/></F></div><button className="primary save">{stock?"Simpan perubahan bahan":"Simpan bahan"}</button></form></>}
function UserForm({submit}:{submit:(e:FormEvent<HTMLFormElement>)=>void}){return <><p className="eyebrow">AKUN & PASSWORD</p><h2>Tambah anggota tim</h2><form onSubmit={submit}><div className="form-grid"><F label="Nama lengkap"><input name="name" required/></F><F label="Jenis pekerjaan / peran"><select name="role"><option>Teknisi</option><option>Asisten Teknisi</option><option>Kurir</option><option>Admin</option></select></F><F label="Username"><input name="username" minLength={4} autoComplete="off" required placeholder="Tanpa spasi"/></F><F label="Password awal"><input type="password" name="password" minLength={8} autoComplete="new-password" required placeholder="Minimal 8 karakter"/></F></div><div className="access-note"><b>Aturan akses</b><p>Admin mengelola operasional dan akun pekerja. Teknisi, Asisten Teknisi, dan Kurir hanya melihat pekerjaan serta fee miliknya sendiri.</p></div><button className="primary save">Buat akun & password</button></form></>}
